<?php

/**
 * CalculateTariffsParametersDTO
 *
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AppYandexSdk\Model;

use AppYandexSdk\ObjectSerializer;
use ArrayAccess;

/**
 * CalculateTariffsParametersDTO Class Doc Comment
 *
 * @category Class
 *
 * @description Параметры для расчета стоимости услуг. Обязательно необходимо указать параметр &#x60;campaignId&#x60; либо &#x60;sellingProgram&#x60;. Совместное использование параметров приведет к ошибке.
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 *
 * @implements \ArrayAccess<string, mixed>
 */
class CalculateTariffsParametersDTO implements \JsonSerializable, ArrayAccess, ModelInterface
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'CalculateTariffsParametersDTO';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'campaign_id' => 'int',
        'selling_program' => '\AppYandexSdk\Model\SellingProgramType',
        'frequency' => '\AppYandexSdk\Model\PaymentFrequencyType',
        'payment_delay_weeks' => 'int',
        'currency' => '\AppYandexSdk\Model\CurrencyType',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     *
     * @phpstan-var array<string, string|null>
     *
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'campaign_id' => 'int64',
        'selling_program' => null,
        'frequency' => null,
        'payment_delay_weeks' => 'int32',
        'currency' => null,
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var bool[]
     */
    protected static array $openAPINullables = [
        'campaign_id' => false,
        'selling_program' => false,
        'frequency' => false,
        'payment_delay_weeks' => false,
        'currency' => false,
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var bool[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return bool[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param  bool[]  $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'campaign_id' => 'campaignId',
        'selling_program' => 'sellingProgram',
        'frequency' => 'frequency',
        'payment_delay_weeks' => 'paymentDelayWeeks',
        'currency' => 'currency',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'campaign_id' => 'setCampaignId',
        'selling_program' => 'setSellingProgram',
        'frequency' => 'setFrequency',
        'payment_delay_weeks' => 'setPaymentDelayWeeks',
        'currency' => 'setCurrency',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'campaign_id' => 'getCampaignId',
        'selling_program' => 'getSellingProgram',
        'frequency' => 'getFrequency',
        'payment_delay_weeks' => 'getPaymentDelayWeeks',
        'currency' => 'getCurrency',
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param  mixed[]|null  $data  Associated array of property values
     *                              initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('campaign_id', $data ?? [], null);
        $this->setIfExists('selling_program', $data ?? [], null);
        $this->setIfExists('frequency', $data ?? [], null);
        $this->setIfExists('payment_delay_weeks', $data ?? [], null);
        $this->setIfExists('currency', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param  mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (! is_null($this->container['campaign_id']) && ($this->container['campaign_id'] < 1)) {
            $invalidProperties[] = "invalid value for 'campaign_id', must be bigger than or equal to 1.";
        }

        if (! is_null($this->container['payment_delay_weeks']) && ($this->container['payment_delay_weeks'] > 4)) {
            $invalidProperties[] = "invalid value for 'payment_delay_weeks', must be smaller than or equal to 4.";
        }

        if (! is_null($this->container['payment_delay_weeks']) && ($this->container['payment_delay_weeks'] < 0)) {
            $invalidProperties[] = "invalid value for 'payment_delay_weeks', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    /**
     * Gets campaign_id
     *
     * @return int|null
     */
    public function getCampaignId()
    {
        return $this->container['campaign_id'];
    }

    /**
     * Sets campaign_id
     *
     * @param  int|null  $campaign_id  Идентификатор кампании (магазина) — технический идентификатор, который представляет ваш магазин в системе Яндекс Маркета при работе через API. Он однозначно связывается с вашим магазином, но предназначен только для автоматизированного взаимодействия.  Его можно узнать с помощью запроса [GET v2/campaigns](../../reference/campaigns/getCampaigns.md) или найти в кабинете продавца на Маркете. Нажмите на иконку вашего аккаунта → **Настройки** и в меню слева выберите **API и модули**:  * блок **Идентификатор кампании**; * вкладка **Лог запросов** → выпадающий список в блоке **Показывать логи**.  ⚠️ Не путайте его с: - идентификатором магазина, который отображается в личном кабинете продавца; - рекламными кампаниями.
     * @return self
     */
    public function setCampaignId($campaign_id)
    {
        if (is_null($campaign_id)) {
            throw new \InvalidArgumentException('non-nullable campaign_id cannot be null');
        }

        if (($campaign_id < 1)) {
            throw new \InvalidArgumentException('invalid value for $campaign_id when calling CalculateTariffsParametersDTO., must be bigger than or equal to 1.');
        }

        $this->container['campaign_id'] = $campaign_id;

        return $this;
    }

    /**
     * Gets selling_program
     *
     * @return \AppYandexSdk\Model\SellingProgramType|null
     */
    public function getSellingProgram()
    {
        return $this->container['selling_program'];
    }

    /**
     * Sets selling_program
     *
     * @param  \AppYandexSdk\Model\SellingProgramType|null  $selling_program  selling_program
     * @return self
     */
    public function setSellingProgram($selling_program)
    {
        if (is_null($selling_program)) {
            throw new \InvalidArgumentException('non-nullable selling_program cannot be null');
        }
        $this->container['selling_program'] = $selling_program;

        return $this;
    }

    /**
     * Gets frequency
     *
     * @return \AppYandexSdk\Model\PaymentFrequencyType|null
     */
    public function getFrequency()
    {
        return $this->container['frequency'];
    }

    /**
     * Sets frequency
     *
     * @param  \AppYandexSdk\Model\PaymentFrequencyType|null  $frequency  frequency
     * @return self
     */
    public function setFrequency($frequency)
    {
        if (is_null($frequency)) {
            throw new \InvalidArgumentException('non-nullable frequency cannot be null');
        }
        $this->container['frequency'] = $frequency;

        return $this;
    }

    /**
     * Gets payment_delay_weeks
     *
     * @return int|null
     */
    public function getPaymentDelayWeeks()
    {
        return $this->container['payment_delay_weeks'];
    }

    /**
     * Sets payment_delay_weeks
     *
     * @param  int|null  $payment_delay_weeks  Отсрочка выплат при еженедельном графике — сколько недель назад были доставлены заказы, за которые приходит выплата.  Допустимые значения: 0, 1, 2 или 4.  Значения параметра `paymentDelayWeeks`, отличные от 0, допускаются только вместе с параметром `frequency` равным 'WEEKLY'. Использование других значений параметра `frequency` совместно с `paymentDelayWeeks` приведет к ошибке.
     * @return self
     */
    public function setPaymentDelayWeeks($payment_delay_weeks)
    {
        if (is_null($payment_delay_weeks)) {
            throw new \InvalidArgumentException('non-nullable payment_delay_weeks cannot be null');
        }

        if (($payment_delay_weeks > 4)) {
            throw new \InvalidArgumentException('invalid value for $payment_delay_weeks when calling CalculateTariffsParametersDTO., must be smaller than or equal to 4.');
        }
        if (($payment_delay_weeks < 0)) {
            throw new \InvalidArgumentException('invalid value for $payment_delay_weeks when calling CalculateTariffsParametersDTO., must be bigger than or equal to 0.');
        }

        $this->container['payment_delay_weeks'] = $payment_delay_weeks;

        return $this;
    }

    /**
     * Gets currency
     *
     * @return \AppYandexSdk\Model\CurrencyType|null
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param  \AppYandexSdk\Model\CurrencyType|null  $currency  currency
     * @return self
     */
    public function setCurrency($currency)
    {
        if (is_null($currency)) {
            throw new \InvalidArgumentException('non-nullable currency cannot be null');
        }
        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param  int|string  $offset  Offset
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param  int|string  $offset  Offset
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param  int|null  $offset  Offset
     * @param  mixed  $value  Value to be set
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param  int|string  $offset  Offset
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     *
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     *               of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
