<?php

/**
 * CisStatusType
 *
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AppYandexSdk\Model;

/**
 * CisStatusType Class Doc Comment
 *
 * @category Class
 *
 * @description Статус проверки кода маркировки в системе :no-translate[«Честный ЗНАК»]:  * &#x60;FAILED&#x60; — не удалось проверить код.    Повторите попытку позже или удалите код маркировки.  * &#x60;IN_PROGRESS&#x60; — в процессе проверки.  * &#x60;NOT_ON_VALIDATION&#x60; — код маркировки не отправлен на проверку.  * &#x60;OK&#x60; — проверка успешно пройдена.  * &#x60;INVALID&#x60; — проверка не пройдена. Продажа товара с этим кодом запрещена.
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */
class CisStatusType
{
    /**
     * Possible values of this enum
     */
    public const OK = 'OK';

    public const FAILED = 'FAILED';

    public const IN_PROGRESS = 'IN_PROGRESS';

    public const INVALID = 'INVALID';

    public const NOT_ON_VALIDATION = 'NOT_ON_VALIDATION';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::OK,
            self::FAILED,
            self::IN_PROGRESS,
            self::INVALID,
            self::NOT_ON_VALIDATION,
        ];
    }
}
