<?php

/**
 * GoodsStatsGoodsDTO
 *
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AppYandexSdk\Model;

use AppYandexSdk\ObjectSerializer;
use ArrayAccess;

/**
 * GoodsStatsGoodsDTO Class Doc Comment
 *
 * @category Class
 *
 * @description Информация о товаре.
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 *
 * @implements \ArrayAccess<string, mixed>
 */
class GoodsStatsGoodsDTO implements \JsonSerializable, ArrayAccess, ModelInterface
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'GoodsStatsGoodsDTO';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'shop_sku' => 'string',
        'market_sku' => 'int',
        'name' => 'string',
        'price' => 'float',
        'category_id' => 'int',
        'category_name' => 'string',
        'weight_dimensions' => '\AppYandexSdk\Model\GoodsStatsWeightDimensionsDTO',
        'warehouses' => '\AppYandexSdk\Model\GoodsStatsWarehouseDTO[]',
        'tariffs' => '\AppYandexSdk\Model\TariffDTO[]',
        'pictures' => 'string[]',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     *
     * @phpstan-var array<string, string|null>
     *
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'shop_sku' => null,
        'market_sku' => 'int64',
        'name' => null,
        'price' => null,
        'category_id' => 'int64',
        'category_name' => null,
        'weight_dimensions' => null,
        'warehouses' => null,
        'tariffs' => null,
        'pictures' => null,
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var bool[]
     */
    protected static array $openAPINullables = [
        'shop_sku' => false,
        'market_sku' => false,
        'name' => false,
        'price' => false,
        'category_id' => false,
        'category_name' => false,
        'weight_dimensions' => false,
        'warehouses' => true,
        'tariffs' => true,
        'pictures' => true,
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var bool[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return bool[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param  bool[]  $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'shop_sku' => 'shopSku',
        'market_sku' => 'marketSku',
        'name' => 'name',
        'price' => 'price',
        'category_id' => 'categoryId',
        'category_name' => 'categoryName',
        'weight_dimensions' => 'weightDimensions',
        'warehouses' => 'warehouses',
        'tariffs' => 'tariffs',
        'pictures' => 'pictures',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'shop_sku' => 'setShopSku',
        'market_sku' => 'setMarketSku',
        'name' => 'setName',
        'price' => 'setPrice',
        'category_id' => 'setCategoryId',
        'category_name' => 'setCategoryName',
        'weight_dimensions' => 'setWeightDimensions',
        'warehouses' => 'setWarehouses',
        'tariffs' => 'setTariffs',
        'pictures' => 'setPictures',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'shop_sku' => 'getShopSku',
        'market_sku' => 'getMarketSku',
        'name' => 'getName',
        'price' => 'getPrice',
        'category_id' => 'getCategoryId',
        'category_name' => 'getCategoryName',
        'weight_dimensions' => 'getWeightDimensions',
        'warehouses' => 'getWarehouses',
        'tariffs' => 'getTariffs',
        'pictures' => 'getPictures',
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param  mixed[]|null  $data  Associated array of property values
     *                              initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('shop_sku', $data ?? [], null);
        $this->setIfExists('market_sku', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('price', $data ?? [], null);
        $this->setIfExists('category_id', $data ?? [], null);
        $this->setIfExists('category_name', $data ?? [], null);
        $this->setIfExists('weight_dimensions', $data ?? [], null);
        $this->setIfExists('warehouses', $data ?? [], null);
        $this->setIfExists('tariffs', $data ?? [], null);
        $this->setIfExists('pictures', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param  mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (! is_null($this->container['shop_sku']) && (mb_strlen($this->container['shop_sku']) > 255)) {
            $invalidProperties[] = "invalid value for 'shop_sku', the character length must be smaller than or equal to 255.";
        }

        if (! is_null($this->container['shop_sku']) && (mb_strlen($this->container['shop_sku']) < 1)) {
            $invalidProperties[] = "invalid value for 'shop_sku', the character length must be bigger than or equal to 1.";
        }

        if (! is_null($this->container['shop_sku']) && ! preg_match('/^(?=.*\\S.*)[^\\x00-\\x08\\x0A-\\x1f\\x7f]{1,255}$/', $this->container['shop_sku'])) {
            $invalidProperties[] = "invalid value for 'shop_sku', must be conform to the pattern /^(?=.*\\S.*)[^\\x00-\\x08\\x0A-\\x1f\\x7f]{1,255}$/.";
        }

        if (! is_null($this->container['market_sku']) && ($this->container['market_sku'] < 1)) {
            $invalidProperties[] = "invalid value for 'market_sku', must be bigger than or equal to 1.";
        }

        if (! is_null($this->container['warehouses']) && (count($this->container['warehouses']) < 1)) {
            $invalidProperties[] = "invalid value for 'warehouses', number of items must be greater than or equal to 1.";
        }

        if (! is_null($this->container['tariffs']) && (count($this->container['tariffs']) < 1)) {
            $invalidProperties[] = "invalid value for 'tariffs', number of items must be greater than or equal to 1.";
        }

        if (! is_null($this->container['pictures']) && (count($this->container['pictures']) < 1)) {
            $invalidProperties[] = "invalid value for 'pictures', number of items must be greater than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    /**
     * Gets shop_sku
     *
     * @return string|null
     */
    public function getShopSku()
    {
        return $this->container['shop_sku'];
    }

    /**
     * Sets shop_sku
     *
     * @param  string|null  $shop_sku  Ваш SKU — идентификатор товара в вашей системе.  Правила использования SKU:  * У каждого товара SKU должен быть свой.  * Уже заданный SKU нельзя освободить и использовать заново для другого товара. Каждый товар должен получать новый идентификатор, до того никогда не использовавшийся в вашем каталоге.  SKU товара можно изменить в кабинете продавца на Маркете. О том, как это сделать, читайте [в Справке Маркета для продавцов](https://yandex.ru/support2/marketplace/ru/assortment/operations/edit-sku).  {% note warning %}  Пробельные символы в начале и конце значения автоматически удаляются. Например, `\"  SKU123  \"` и `\"SKU123\"` будут обработаны как одинаковые значения.  {% endnote %}  [Что такое SKU и как его назначать](https://yandex.ru/support/marketplace/assortment/add/index.html#fields)
     * @return self
     */
    public function setShopSku($shop_sku)
    {
        if (is_null($shop_sku)) {
            throw new \InvalidArgumentException('non-nullable shop_sku cannot be null');
        }
        if ((mb_strlen($shop_sku) > 255)) {
            throw new \InvalidArgumentException('invalid length for $shop_sku when calling GoodsStatsGoodsDTO., must be smaller than or equal to 255.');
        }
        if ((mb_strlen($shop_sku) < 1)) {
            throw new \InvalidArgumentException('invalid length for $shop_sku when calling GoodsStatsGoodsDTO., must be bigger than or equal to 1.');
        }
        if ((! preg_match('/^(?=.*\\S.*)[^\\x00-\\x08\\x0A-\\x1f\\x7f]{1,255}$/', ObjectSerializer::toString($shop_sku)))) {
            throw new \InvalidArgumentException('invalid value for $shop_sku when calling GoodsStatsGoodsDTO., must conform to the pattern /^(?=.*\\S.*)[^\\x00-\\x08\\x0A-\\x1f\\x7f]{1,255}$/.');
        }

        $this->container['shop_sku'] = $shop_sku;

        return $this;
    }

    /**
     * Gets market_sku
     *
     * @return int|null
     */
    public function getMarketSku()
    {
        return $this->container['market_sku'];
    }

    /**
     * Sets market_sku
     *
     * @param  int|null  $market_sku  Идентификатор карточки товара на Маркете.
     * @return self
     */
    public function setMarketSku($market_sku)
    {
        if (is_null($market_sku)) {
            throw new \InvalidArgumentException('non-nullable market_sku cannot be null');
        }

        if (($market_sku < 1)) {
            throw new \InvalidArgumentException('invalid value for $market_sku when calling GoodsStatsGoodsDTO., must be bigger than or equal to 1.');
        }

        $this->container['market_sku'] = $market_sku;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param  string|null  $name  Название товара.
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets price
     *
     * @return float|null
     */
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price
     *
     * @param  float|null  $price  Цена товара в валюте, которая установлена [в кабинете продавца на Маркете](https://partner.market.yandex.ru/).
     * @return self
     */
    public function setPrice($price)
    {
        if (is_null($price)) {
            throw new \InvalidArgumentException('non-nullable price cannot be null');
        }
        $this->container['price'] = $price;

        return $this;
    }

    /**
     * Gets category_id
     *
     * @return int|null
     */
    public function getCategoryId()
    {
        return $this->container['category_id'];
    }

    /**
     * Sets category_id
     *
     * @param  int|null  $category_id  Идентификатор категории товара на Маркете.
     * @return self
     */
    public function setCategoryId($category_id)
    {
        if (is_null($category_id)) {
            throw new \InvalidArgumentException('non-nullable category_id cannot be null');
        }
        $this->container['category_id'] = $category_id;

        return $this;
    }

    /**
     * Gets category_name
     *
     * @return string|null
     */
    public function getCategoryName()
    {
        return $this->container['category_name'];
    }

    /**
     * Sets category_name
     *
     * @param  string|null  $category_name  Название категории товара на Маркете.
     * @return self
     */
    public function setCategoryName($category_name)
    {
        if (is_null($category_name)) {
            throw new \InvalidArgumentException('non-nullable category_name cannot be null');
        }
        $this->container['category_name'] = $category_name;

        return $this;
    }

    /**
     * Gets weight_dimensions
     *
     * @return \AppYandexSdk\Model\GoodsStatsWeightDimensionsDTO|null
     */
    public function getWeightDimensions()
    {
        return $this->container['weight_dimensions'];
    }

    /**
     * Sets weight_dimensions
     *
     * @param  \AppYandexSdk\Model\GoodsStatsWeightDimensionsDTO|null  $weight_dimensions  weight_dimensions
     * @return self
     */
    public function setWeightDimensions($weight_dimensions)
    {
        if (is_null($weight_dimensions)) {
            throw new \InvalidArgumentException('non-nullable weight_dimensions cannot be null');
        }
        $this->container['weight_dimensions'] = $weight_dimensions;

        return $this;
    }

    /**
     * Gets warehouses
     *
     * @return \AppYandexSdk\Model\GoodsStatsWarehouseDTO[]|null
     */
    public function getWarehouses()
    {
        return $this->container['warehouses'];
    }

    /**
     * Sets warehouses
     *
     * @param  \AppYandexSdk\Model\GoodsStatsWarehouseDTO[]|null  $warehouses  Информация о складах, на которых хранится товар.  Параметр не приходит, если товара нет ни на одном складе.
     * @return self
     */
    public function setWarehouses($warehouses)
    {
        if (is_null($warehouses)) {
            array_push($this->openAPINullablesSetToNull, 'warehouses');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('warehouses', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (! is_null($warehouses) && (count($warehouses) < 1)) {
            throw new \InvalidArgumentException('invalid length for $warehouses when calling GoodsStatsGoodsDTO., number of items must be greater than or equal to 1.');
        }
        $this->container['warehouses'] = $warehouses;

        return $this;
    }

    /**
     * Gets tariffs
     *
     * @return \AppYandexSdk\Model\TariffDTO[]|null
     */
    public function getTariffs()
    {
        return $this->container['tariffs'];
    }

    /**
     * Sets tariffs
     *
     * @param  \AppYandexSdk\Model\TariffDTO[]|null  $tariffs  Информация о тарифах, по которым нужно заплатить за услуги Маркета.  По некоторым услугам могут возвращаться несколько разных стоимостей. Например, в модели FBS стоимость услуги `SORTING` (обработка заказа) зависит от способа отгрузки и количества заказов в отгрузке. Подробнее о тарифах на услуги читайте [в Справке Маркета для продавцов](https://yandex.ru/support2/marketplace/ru/introduction/rates/models/).
     * @return self
     */
    public function setTariffs($tariffs)
    {
        if (is_null($tariffs)) {
            array_push($this->openAPINullablesSetToNull, 'tariffs');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('tariffs', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (! is_null($tariffs) && (count($tariffs) < 1)) {
            throw new \InvalidArgumentException('invalid length for $tariffs when calling GoodsStatsGoodsDTO., number of items must be greater than or equal to 1.');
        }
        $this->container['tariffs'] = $tariffs;

        return $this;
    }

    /**
     * Gets pictures
     *
     * @return string[]|null
     */
    public function getPictures()
    {
        return $this->container['pictures'];
    }

    /**
     * Sets pictures
     *
     * @param  string[]|null  $pictures  Ссылки (URL) изображений товара в хорошем качестве.
     * @return self
     */
    public function setPictures($pictures)
    {
        if (is_null($pictures)) {
            array_push($this->openAPINullablesSetToNull, 'pictures');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('pictures', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (! is_null($pictures) && (count($pictures) < 1)) {
            throw new \InvalidArgumentException('invalid length for $pictures when calling GoodsStatsGoodsDTO., number of items must be greater than or equal to 1.');
        }
        $this->container['pictures'] = $pictures;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param  int|string  $offset  Offset
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param  int|string  $offset  Offset
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param  int|null  $offset  Offset
     * @param  mixed  $value  Value to be set
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param  int|string  $offset  Offset
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     *
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     *               of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
