<?php

/**
 * LogisticPointBrandType
 *
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AppYandexSdk\Model;

/**
 * LogisticPointBrandType Class Doc Comment
 *
 * @category Class
 *
 * @description Тип пункта выдачи:  * &#x60;MARKET&#x60; — пункт выдачи Маркета.
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */
class LogisticPointBrandType
{
    /**
     * Possible values of this enum
     */
    public const MARKET = 'MARKET';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::MARKET,
        ];
    }
}
