<?php

/**
 * OfferDefaultPriceDTO
 *
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AppYandexSdk\Model;

use AppYandexSdk\ObjectSerializer;
use ArrayAccess;

/**
 * OfferDefaultPriceDTO Class Doc Comment
 *
 * @category Class
 *
 * @description Цена с указанием валюты, скидки и времени последнего обновления, а также минимальная цена для попадания в акцию «Бестселлеры Маркета».
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 *
 * @implements \ArrayAccess<string, mixed>
 */
class OfferDefaultPriceDTO implements \JsonSerializable, ArrayAccess, ModelInterface
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'OfferDefaultPriceDTO';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'minimum_for_bestseller' => 'float',
        'excluded_from_bestsellers' => 'bool',
        'value' => 'float',
        'currency_id' => '\AppYandexSdk\Model\CurrencyType',
        'discount_base' => 'float',
        'updated_at' => '\DateTime',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     *
     * @phpstan-var array<string, string|null>
     *
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'minimum_for_bestseller' => null,
        'excluded_from_bestsellers' => null,
        'value' => null,
        'currency_id' => null,
        'discount_base' => null,
        'updated_at' => 'date-time',
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var bool[]
     */
    protected static array $openAPINullables = [
        'minimum_for_bestseller' => false,
        'excluded_from_bestsellers' => false,
        'value' => false,
        'currency_id' => false,
        'discount_base' => false,
        'updated_at' => false,
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var bool[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return bool[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param  bool[]  $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'minimum_for_bestseller' => 'minimumForBestseller',
        'excluded_from_bestsellers' => 'excludedFromBestsellers',
        'value' => 'value',
        'currency_id' => 'currencyId',
        'discount_base' => 'discountBase',
        'updated_at' => 'updatedAt',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'minimum_for_bestseller' => 'setMinimumForBestseller',
        'excluded_from_bestsellers' => 'setExcludedFromBestsellers',
        'value' => 'setValue',
        'currency_id' => 'setCurrencyId',
        'discount_base' => 'setDiscountBase',
        'updated_at' => 'setUpdatedAt',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'minimum_for_bestseller' => 'getMinimumForBestseller',
        'excluded_from_bestsellers' => 'getExcludedFromBestsellers',
        'value' => 'getValue',
        'currency_id' => 'getCurrencyId',
        'discount_base' => 'getDiscountBase',
        'updated_at' => 'getUpdatedAt',
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param  mixed[]|null  $data  Associated array of property values
     *                              initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('minimum_for_bestseller', $data ?? [], null);
        $this->setIfExists('excluded_from_bestsellers', $data ?? [], null);
        $this->setIfExists('value', $data ?? [], null);
        $this->setIfExists('currency_id', $data ?? [], null);
        $this->setIfExists('discount_base', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param  mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (! is_null($this->container['minimum_for_bestseller']) && ($this->container['minimum_for_bestseller'] > 100000000)) {
            $invalidProperties[] = "invalid value for 'minimum_for_bestseller', must be smaller than or equal to 100000000.";
        }

        if (! is_null($this->container['minimum_for_bestseller']) && ($this->container['minimum_for_bestseller'] <= 0)) {
            $invalidProperties[] = "invalid value for 'minimum_for_bestseller', must be bigger than 0.";
        }

        if (! is_null($this->container['value']) && ($this->container['value'] <= 0)) {
            $invalidProperties[] = "invalid value for 'value', must be bigger than 0.";
        }

        if (! is_null($this->container['discount_base']) && ($this->container['discount_base'] <= 0)) {
            $invalidProperties[] = "invalid value for 'discount_base', must be bigger than 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    /**
     * Gets minimum_for_bestseller
     *
     * @return float|null
     */
    public function getMinimumForBestseller()
    {
        return $this->container['minimum_for_bestseller'];
    }

    /**
     * Sets minimum_for_bestseller
     *
     * @param  float|null  $minimum_for_bestseller  Минимальная цена товара для попадания в акцию «Бестселлеры Маркета». Подробнее об этом способе участия читайте [в Справке Маркета для продавцов](https://yandex.ru/support/marketplace/ru/marketing/promos/market/bestsellers#minimum).  Передается в методе [POST v2/businesses/{businessId}/offer-prices/updates](../../reference/business-assortment/updateBusinessPrices.md).
     * @return self
     */
    public function setMinimumForBestseller($minimum_for_bestseller)
    {
        if (is_null($minimum_for_bestseller)) {
            throw new \InvalidArgumentException('non-nullable minimum_for_bestseller cannot be null');
        }

        if (($minimum_for_bestseller > 100000000)) {
            throw new \InvalidArgumentException('invalid value for $minimum_for_bestseller when calling OfferDefaultPriceDTO., must be smaller than or equal to 100000000.');
        }
        if (($minimum_for_bestseller <= 0)) {
            throw new \InvalidArgumentException('invalid value for $minimum_for_bestseller when calling OfferDefaultPriceDTO., must be bigger than 0.');
        }

        $this->container['minimum_for_bestseller'] = $minimum_for_bestseller;

        return $this;
    }

    /**
     * Gets excluded_from_bestsellers
     *
     * @return bool|null
     */
    public function getExcludedFromBestsellers()
    {
        return $this->container['excluded_from_bestsellers'];
    }

    /**
     * Sets excluded_from_bestsellers
     *
     * @param  bool|null  $excluded_from_bestsellers  Признак того, что товар не попадает в акцию «Бестселлеры Маркета». Подробнее об акции читайте [в Справке Маркета для продавцов](https://yandex.ru/support2/marketplace/ru/marketing/promos/market/bestsellers).  Если значение `true`, в методе [POST v2/businesses/{businessId}/offer-prices/updates](../../reference/business-assortment/updateBusinessPrices.md) параметр `minimumForBestseller` игнорируется.
     * @return self
     */
    public function setExcludedFromBestsellers($excluded_from_bestsellers)
    {
        if (is_null($excluded_from_bestsellers)) {
            throw new \InvalidArgumentException('non-nullable excluded_from_bestsellers cannot be null');
        }
        $this->container['excluded_from_bestsellers'] = $excluded_from_bestsellers;

        return $this;
    }

    /**
     * Gets value
     *
     * @return float|null
     */
    public function getValue()
    {
        return $this->container['value'];
    }

    /**
     * Sets value
     *
     * @param  float|null  $value  Цена товара.
     * @return self
     */
    public function setValue($value)
    {
        if (is_null($value)) {
            throw new \InvalidArgumentException('non-nullable value cannot be null');
        }

        if (($value <= 0)) {
            throw new \InvalidArgumentException('invalid value for $value when calling OfferDefaultPriceDTO., must be bigger than 0.');
        }

        $this->container['value'] = $value;

        return $this;
    }

    /**
     * Gets currency_id
     *
     * @return \AppYandexSdk\Model\CurrencyType|null
     */
    public function getCurrencyId()
    {
        return $this->container['currency_id'];
    }

    /**
     * Sets currency_id
     *
     * @param  \AppYandexSdk\Model\CurrencyType|null  $currency_id  currency_id
     * @return self
     */
    public function setCurrencyId($currency_id)
    {
        if (is_null($currency_id)) {
            throw new \InvalidArgumentException('non-nullable currency_id cannot be null');
        }
        $this->container['currency_id'] = $currency_id;

        return $this;
    }

    /**
     * Gets discount_base
     *
     * @return float|null
     */
    public function getDiscountBase()
    {
        return $this->container['discount_base'];
    }

    /**
     * Sets discount_base
     *
     * @param  float|null  $discount_base  Зачеркнутая цена.  Число должно быть целым. Вы можете указать цену со скидкой от 5 до 99%.  Передавайте этот параметр при каждом обновлении цены, если предоставляете скидку на товар.
     * @return self
     */
    public function setDiscountBase($discount_base)
    {
        if (is_null($discount_base)) {
            throw new \InvalidArgumentException('non-nullable discount_base cannot be null');
        }

        if (($discount_base <= 0)) {
            throw new \InvalidArgumentException('invalid value for $discount_base when calling OfferDefaultPriceDTO., must be bigger than 0.');
        }

        $this->container['discount_base'] = $discount_base;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime|null
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param  \DateTime|null  $updated_at  Время последнего обновления.
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            throw new \InvalidArgumentException('non-nullable updated_at cannot be null');
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param  int|string  $offset  Offset
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param  int|string  $offset  Offset
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param  int|null  $offset  Offset
     * @param  mixed  $value  Value to be set
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param  int|string  $offset  Offset
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     *
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     *               of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
