<?php

/**
 * OrderDatesFilterDTO
 *
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AppYandexSdk\Model;

use AppYandexSdk\ObjectSerializer;
use ArrayAccess;

/**
 * OrderDatesFilterDTO Class Doc Comment
 *
 * @category Class
 *
 * @description Фильтр по датам заказов.
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 *
 * @implements \ArrayAccess<string, mixed>
 */
class OrderDatesFilterDTO implements \JsonSerializable, ArrayAccess, ModelInterface
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'OrderDatesFilterDTO';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'creation_date_from' => '\DateTime',
        'creation_date_to' => '\DateTime',
        'shipment_date_from' => '\DateTime',
        'shipment_date_to' => '\DateTime',
        'update_date_from' => '\DateTime',
        'update_date_to' => '\DateTime',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     *
     * @phpstan-var array<string, string|null>
     *
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'creation_date_from' => 'date',
        'creation_date_to' => 'date',
        'shipment_date_from' => 'date',
        'shipment_date_to' => 'date',
        'update_date_from' => 'date-time',
        'update_date_to' => 'date-time',
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var bool[]
     */
    protected static array $openAPINullables = [
        'creation_date_from' => false,
        'creation_date_to' => false,
        'shipment_date_from' => false,
        'shipment_date_to' => false,
        'update_date_from' => false,
        'update_date_to' => false,
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var bool[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return bool[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param  bool[]  $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'creation_date_from' => 'creationDateFrom',
        'creation_date_to' => 'creationDateTo',
        'shipment_date_from' => 'shipmentDateFrom',
        'shipment_date_to' => 'shipmentDateTo',
        'update_date_from' => 'updateDateFrom',
        'update_date_to' => 'updateDateTo',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'creation_date_from' => 'setCreationDateFrom',
        'creation_date_to' => 'setCreationDateTo',
        'shipment_date_from' => 'setShipmentDateFrom',
        'shipment_date_to' => 'setShipmentDateTo',
        'update_date_from' => 'setUpdateDateFrom',
        'update_date_to' => 'setUpdateDateTo',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'creation_date_from' => 'getCreationDateFrom',
        'creation_date_to' => 'getCreationDateTo',
        'shipment_date_from' => 'getShipmentDateFrom',
        'shipment_date_to' => 'getShipmentDateTo',
        'update_date_from' => 'getUpdateDateFrom',
        'update_date_to' => 'getUpdateDateTo',
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param  mixed[]|null  $data  Associated array of property values
     *                              initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('creation_date_from', $data ?? [], null);
        $this->setIfExists('creation_date_to', $data ?? [], null);
        $this->setIfExists('shipment_date_from', $data ?? [], null);
        $this->setIfExists('shipment_date_to', $data ?? [], null);
        $this->setIfExists('update_date_from', $data ?? [], null);
        $this->setIfExists('update_date_to', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param  mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    /**
     * Gets creation_date_from
     *
     * @return \DateTime|null
     */
    public function getCreationDateFrom()
    {
        return $this->container['creation_date_from'];
    }

    /**
     * Sets creation_date_from
     *
     * @param  \DateTime|null  $creation_date_from  Начальная дата для фильтрации заказов по дате оформления.  Формат даты: `ГГГГ-ММ-ДД`.  Между начальной и конечной датой (параметр `creationDateTo`) должно быть не больше 30 дней.  Значение по умолчанию: 30 дней назад от текущей даты.  Начальная дата включается в интервал для фильтрации.
     * @return self
     */
    public function setCreationDateFrom($creation_date_from)
    {
        if (is_null($creation_date_from)) {
            throw new \InvalidArgumentException('non-nullable creation_date_from cannot be null');
        }
        $this->container['creation_date_from'] = $creation_date_from;

        return $this;
    }

    /**
     * Gets creation_date_to
     *
     * @return \DateTime|null
     */
    public function getCreationDateTo()
    {
        return $this->container['creation_date_to'];
    }

    /**
     * Sets creation_date_to
     *
     * @param  \DateTime|null  $creation_date_to  Конечная дата для фильтрации заказов по дате оформления.  Формат даты: `ГГГГ-ММ-ДД`.  Между начальной (параметр `creationDateFrom`) и конечной датой должно быть не больше 30 дней.  Значение по умолчанию: текущая дата.  Если промежуток времени между `creationDateTo` и `creationDateFrom` меньше суток, то `creationDateTo` равен `creationDateFrom` + сутки.  Конечная дата не включается в интервал для фильтрации.
     * @return self
     */
    public function setCreationDateTo($creation_date_to)
    {
        if (is_null($creation_date_to)) {
            throw new \InvalidArgumentException('non-nullable creation_date_to cannot be null');
        }
        $this->container['creation_date_to'] = $creation_date_to;

        return $this;
    }

    /**
     * Gets shipment_date_from
     *
     * @return \DateTime|null
     */
    public function getShipmentDateFrom()
    {
        return $this->container['shipment_date_from'];
    }

    /**
     * Sets shipment_date_from
     *
     * @param  \DateTime|null  $shipment_date_from  Начальная дата для фильтрации заказов по дате отгрузки в службу доставки (параметр `shipmentDate`).  Формат даты: `ГГГГ-ММ-ДД`.  Между начальной и конечной датой (параметр `shipmentDateTo`) должно быть не больше 30 дней.  Начальная дата включается в интервал для фильтрации.
     * @return self
     */
    public function setShipmentDateFrom($shipment_date_from)
    {
        if (is_null($shipment_date_from)) {
            throw new \InvalidArgumentException('non-nullable shipment_date_from cannot be null');
        }
        $this->container['shipment_date_from'] = $shipment_date_from;

        return $this;
    }

    /**
     * Gets shipment_date_to
     *
     * @return \DateTime|null
     */
    public function getShipmentDateTo()
    {
        return $this->container['shipment_date_to'];
    }

    /**
     * Sets shipment_date_to
     *
     * @param  \DateTime|null  $shipment_date_to  Конечная дата для фильтрации заказов по дате отгрузки в службу доставки (параметр `shipmentDate`).  Формат даты: `ГГГГ-ММ-ДД`.  Между начальной (параметр `shipmentDateFrom`) и конечной датой должно быть не больше 30 дней.  Если промежуток времени между `shipmentDateTo` и `shipmentDateFrom` меньше суток, то `shipmentDateTo` равен `shipmentDateFrom` + сутки.  Конечная дата не включается в интервал для фильтрации.
     * @return self
     */
    public function setShipmentDateTo($shipment_date_to)
    {
        if (is_null($shipment_date_to)) {
            throw new \InvalidArgumentException('non-nullable shipment_date_to cannot be null');
        }
        $this->container['shipment_date_to'] = $shipment_date_to;

        return $this;
    }

    /**
     * Gets update_date_from
     *
     * @return \DateTime|null
     */
    public function getUpdateDateFrom()
    {
        return $this->container['update_date_from'];
    }

    /**
     * Sets update_date_from
     *
     * @param  \DateTime|null  $update_date_from  Начальная дата обновления заказа (ISO 8601).
     * @return self
     */
    public function setUpdateDateFrom($update_date_from)
    {
        if (is_null($update_date_from)) {
            throw new \InvalidArgumentException('non-nullable update_date_from cannot be null');
        }
        $this->container['update_date_from'] = $update_date_from;

        return $this;
    }

    /**
     * Gets update_date_to
     *
     * @return \DateTime|null
     */
    public function getUpdateDateTo()
    {
        return $this->container['update_date_to'];
    }

    /**
     * Sets update_date_to
     *
     * @param  \DateTime|null  $update_date_to  Конечная дата обновления заказа (ISO 8601).
     * @return self
     */
    public function setUpdateDateTo($update_date_to)
    {
        if (is_null($update_date_to)) {
            throw new \InvalidArgumentException('non-nullable update_date_to cannot be null');
        }
        $this->container['update_date_to'] = $update_date_to;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param  int|string  $offset  Offset
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param  int|string  $offset  Offset
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param  int|null  $offset  Offset
     * @param  mixed  $value  Value to be set
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param  int|string  $offset  Offset
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     *
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     *               of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
