<?php

/**
 * OrderCancellationReasonType
 *
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AppYandexSdk\Model;

/**
 * OrderCancellationReasonType Class Doc Comment
 *
 * @category Class
 *
 * @description Варианты причин, по которым заказ не может быть отменен.  * &#x60;ORDER_DELIVERED&#x60; — заказ уже доставлен. * &#x60;ORDER_IN_DELIVERY&#x60; — заказ уже у курьера.
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */
class OrderCancellationReasonType
{
    /**
     * Possible values of this enum
     */
    public const ORDER_DELIVERED = 'ORDER_DELIVERED';

    public const ORDER_IN_DELIVERY = 'ORDER_IN_DELIVERY';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ORDER_DELIVERED,
            self::ORDER_IN_DELIVERY,
        ];
    }
}
