<?php

/**
 * PromoOfferParticipationStatusMultiFilterType
 *
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AppYandexSdk\Model;

/**
 * PromoOfferParticipationStatusMultiFilterType Class Doc Comment
 *
 * @category Class
 *
 * @description Фильтр для товаров, которые могут участвовать в акции:  * &#x60;MANUALLY_ADDED&#x60; — товары, которые добавлены вручную.  * &#x60;RENEWED&#x60; — товары, которые добавлены автоматически из предыдущей акции «Бестселлеры Маркета». Только для акций «Бестселлеры Маркета».  * &#x60;RENEW_FAILED&#x60; — товары, которые не получилось перенести из предыдущей акции «Бестселлеры Маркета». Только для акций «Бестселлеры Маркета».  * &#x60;NOT_MANUALLY_ADDED&#x60; — товары, которые не участвуют в акции и те, которые добавлены автоматически.  * &#x60;MINIMUM_FOR_PROMOS&#x60; — товары с [установленным минимумом по цене для акций](*minimumForBestseller), который соответствует порогу &#x60;maxPromoPrice&#x60;. Такие товары участвуют в акции с ценой &#x60;maxPromoPrice&#x60;. Только для акций «Бестселлеры Маркета».  Если не передать параметр &#x60;statuses&#x60;, вернутся все товары.  Об автоматическом и ручном добавлении товаров в акцию читайте [в Справке Маркета для продавцов](https://yandex.ru/support2/marketplace/ru/marketing/promos/market/index).
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */
class PromoOfferParticipationStatusMultiFilterType
{
    /**
     * Possible values of this enum
     */
    public const MANUALLY_ADDED = 'MANUALLY_ADDED';

    public const RENEWED = 'RENEWED';

    public const RENEW_FAILED = 'RENEW_FAILED';

    public const NOT_MANUALLY_ADDED = 'NOT_MANUALLY_ADDED';

    public const MINIMUM_FOR_PROMOS = 'MINIMUM_FOR_PROMOS';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::MANUALLY_ADDED,
            self::RENEWED,
            self::RENEW_FAILED,
            self::NOT_MANUALLY_ADDED,
            self::MINIMUM_FOR_PROMOS,
        ];
    }
}
