<?php

/**
 * QuestionsTextEntityType
 *
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AppYandexSdk\Model;

/**
 * QuestionsTextEntityType Class Doc Comment
 *
 * @category Class
 *
 * @description Тип сущности:  * &#x60;QUESTION&#x60; — вопрос о товаре. * &#x60;ANSWER&#x60; — ответ на вопрос. * &#x60;COMMENT&#x60; — комментарий к ответу.
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */
class QuestionsTextEntityType
{
    /**
     * Possible values of this enum
     */
    public const QUESTION = 'QUESTION';

    public const ANSWER = 'ANSWER';

    public const COMMENT = 'COMMENT';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::QUESTION,
            self::ANSWER,
            self::COMMENT,
        ];
    }
}
