<?php

/**
 * ReturnRequestDecisionReasonType
 *
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AppYandexSdk\Model;

/**
 * ReturnRequestDecisionReasonType Class Doc Comment
 *
 * @category Class
 *
 * @description Причина отказа:  * &#x60;ISSUE_WITH_THE_PRODUCT_WAS_NOT_CONFIRMED&#x60; — проблема с товаром не подтвердилась. * &#x60;MECHANICAL_DAMAGE&#x60; — есть механические повреждения товара. * &#x60;WARRANTY_PERIOD_HAS_EXPIRED&#x60; — истек гарантийный срок. * &#x60;CONFIGURATION_OR_PACKAGING_COMPROMISED&#x60; — нарушена комплектация или упаковка. * &#x60;PRODUCT_APPEARANCE_COMPROMISED&#x60; — нарушен товарный вид. * &#x60;WARRANTY_TERMS_VIOLATED&#x60; — нарушены условия гарантии. * &#x60;DEVICE_ACTIVATED&#x60; — устройство активировано.
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */
class ReturnRequestDecisionReasonType
{
    /**
     * Possible values of this enum
     */
    public const ISSUE_WITH_THE_PRODUCT_WAS_NOT_CONFIRMED = 'ISSUE_WITH_THE_PRODUCT_WAS_NOT_CONFIRMED';

    public const MECHANICAL_DAMAGE = 'MECHANICAL_DAMAGE';

    public const WARRANTY_PERIOD_HAS_EXPIRED = 'WARRANTY_PERIOD_HAS_EXPIRED';

    public const CONFIGURATION_OR_PACKAGING_COMPROMISED = 'CONFIGURATION_OR_PACKAGING_COMPROMISED';

    public const PRODUCT_APPEARANCE_COMPROMISED = 'PRODUCT_APPEARANCE_COMPROMISED';

    public const WARRANTY_TERMS_VIOLATED = 'WARRANTY_TERMS_VIOLATED';

    public const DEVICE_ACTIVATED = 'DEVICE_ACTIVATED';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ISSUE_WITH_THE_PRODUCT_WAS_NOT_CONFIRMED,
            self::MECHANICAL_DAMAGE,
            self::WARRANTY_PERIOD_HAS_EXPIRED,
            self::CONFIGURATION_OR_PACKAGING_COMPROMISED,
            self::PRODUCT_APPEARANCE_COMPROMISED,
            self::WARRANTY_TERMS_VIOLATED,
            self::DEVICE_ACTIVATED,
        ];
    }
}
