<?php

/**
 * SupplyRequestLocationType
 *
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AppYandexSdk\Model;

/**
 * SupplyRequestLocationType Class Doc Comment
 *
 * @category Class
 *
 * @description Тип склада или ПВЗ:  * &#x60;FULFILLMENT&#x60; — склад хранения. * &#x60;XDOC&#x60; — транзитный склад. * &#x60;PICKUP_POINT&#x60; — ПВЗ.
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */
class SupplyRequestLocationType
{
    /**
     * Possible values of this enum
     */
    public const FULFILLMENT = 'FULFILLMENT';

    public const XDOC = 'XDOC';

    public const PICKUP_POINT = 'PICKUP_POINT';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::FULFILLMENT,
            self::XDOC,
            self::PICKUP_POINT,
        ];
    }
}
