<?php

/**
 * WarehouseStatusType
 *
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AppYandexSdk\Model;

/**
 * WarehouseStatusType Class Doc Comment
 *
 * @category Class
 *
 * @description Статус склада:  * &#x60;DISABLED_MANUALLY&#x60; – отключен вами. * &#x60;OTHER&#x60; – другой статус. Например, склад включен или отключен Маркетом.
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */
class WarehouseStatusType
{
    /**
     * Possible values of this enum
     */
    public const DISABLED_MANUALLY = 'DISABLED_MANUALLY';

    public const OTHER = 'OTHER';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DISABLED_MANUALLY,
            self::OTHER,
        ];
    }
}
