<?php

/**
 * OrdersApiTest
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace AppYandexSdk\Test\Api;

use PHPUnit\Framework\TestCase;

/**
 * OrdersApiTest Class Doc Comment
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */
class OrdersApiTest extends TestCase
{
    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void {}

    /**
     * Setup before running each test case
     */
    protected function setUp(): void {}

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void {}

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void {}

    /**
     * Test case for acceptOrderCancellation
     *
     * Отмена заказа покупателем.
     */
    public function test_accept_order_cancellation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createOrder
     *
     * Создание заказа.
     */
    public function test_create_order()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBusinessOrders
     *
     * Информация о заказах в кабинете.
     */
    public function test_get_business_orders()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOrder
     *
     * Информация об одном заказе в магазине.
     */
    public function test_get_order()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOrderIdentifiersStatus
     *
     * Статусы проверки кодов маркировки.
     */
    public function test_get_order_identifiers_status()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOrderUpdateOptions
     *
     * Получение временных интервалов для изменения заказа.
     */
    public function test_get_order_update_options()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOrders
     *
     * Информация о заказах в магазине.
     */
    public function test_get_orders()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for provideOrderDigitalCodes
     *
     * Передача ключей цифровых товаров.
     */
    public function test_provide_order_digital_codes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for provideOrderItemIdentifiers
     *
     * Передача кодов маркировки единиц товара.
     */
    public function test_provide_order_item_identifiers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setOrderBoxLayout
     *
     * Подготовка заказа.
     */
    public function test_set_order_box_layout()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setOrderShipmentBoxes
     *
     * Передача количества грузовых мест в заказе.
     */
    public function test_set_order_shipment_boxes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateExternalOrderId
     *
     * Передача внешнего идентификатора заказа.
     */
    public function test_update_external_order_id()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateOrder
     *
     * Изменение заказа.
     */
    public function test_update_order()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateOrderItems
     *
     * Удаление товаров из заказа или уменьшение их числа.
     */
    public function test_update_order_items()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateOrderStatus
     *
     * Изменение статуса одного заказа.
     */
    public function test_update_order_status()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateOrderStatuses
     *
     * Изменение статусов нескольких заказов.
     */
    public function test_update_order_statuses()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
