<?php

/**
 * ShipmentsApiTest
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace AppYandexSdk\Test\Api;

use PHPUnit\Framework\TestCase;

/**
 * ShipmentsApiTest Class Doc Comment
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */
class ShipmentsApiTest extends TestCase
{
    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void {}

    /**
     * Setup before running each test case
     */
    protected function setUp(): void {}

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void {}

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void {}

    /**
     * Test case for confirmShipment
     *
     * Подтверждение отгрузки.
     */
    public function test_confirm_shipment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for downloadShipmentAct
     *
     * Получение акта приема-передачи.
     */
    public function test_download_shipment_act()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for downloadShipmentDiscrepancyAct
     *
     * Получение акта расхождений.
     */
    public function test_download_shipment_discrepancy_act()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for downloadShipmentInboundAct
     *
     * Получение фактического акта приема-передачи.
     */
    public function test_download_shipment_inbound_act()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for downloadShipmentPalletLabels
     *
     * Ярлыки для доверительной приемки.
     */
    public function test_download_shipment_pallet_labels()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for downloadShipmentReceptionTransferAct
     *
     * Подтверждение ближайшей отгрузки и получение акта приема-передачи для нее.
     */
    public function test_download_shipment_reception_transfer_act()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for downloadShipmentTransportationWaybill
     *
     * Получение транспортной накладной.
     */
    public function test_download_shipment_transportation_waybill()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getShipment
     *
     * Получение информации об одной отгрузке.
     */
    public function test_get_shipment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getShipmentOrdersInfo
     *
     * Получение информации о возможности печати ярлыков.
     */
    public function test_get_shipment_orders_info()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchShipments
     *
     * Получение информации о нескольких отгрузках.
     */
    public function test_search_shipments()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setShipmentPalletsCount
     *
     * Передача количества упаковок для доверительной приемки.
     */
    public function test_set_shipment_pallets_count()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for transferOrdersFromShipment
     *
     * Перенос заказов в следующую отгрузку.
     */
    public function test_transfer_orders_from_shipment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
