<?php

/**
 * SupplyRequestsApiTest
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace AppYandexSdk\Test\Api;

use PHPUnit\Framework\TestCase;

/**
 * SupplyRequestsApiTest Class Doc Comment
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */
class SupplyRequestsApiTest extends TestCase
{
    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void {}

    /**
     * Setup before running each test case
     */
    protected function setUp(): void {}

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void {}

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void {}

    /**
     * Test case for getSupplyRequestDocuments
     *
     * Получение документов по заявке на поставку, вывоз или утилизацию.
     */
    public function test_get_supply_request_documents()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSupplyRequestItems
     *
     * Получение товаров в заявке на поставку, вывоз или утилизацию.
     */
    public function test_get_supply_request_items()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSupplyRequests
     *
     * Получение информации о заявках на поставку, вывоз и утилизацию.
     */
    public function test_get_supply_requests()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
