<?php

return [
    'services' => [
        'b2b-marketplace-onboarding' => [
            'name' => 'B2B marketplace onboarding',
            'service_type' => 'merchant_onboarding',
            'audience' => ['digital goods sellers', 'voucher distributors', 'B2B partners'],
            'description' => 'Business profile, seller identity, legal entity setup, storefront activation, and channel readiness inside Meanly.',
            'deliverable' => 'Activated Meanly business profile with seller workspace, shop settings, storefront eligibility, and API/channel readiness checklist.',
            'outcome' => 'A seller can start managing digital product inventory, checkout, orders, and fulfillment through Meanly.',
            'delivery_time' => 'same day after verification',
            'sla' => 'Initial setup review within 1 business day',
            'execution_mode' => 'managed_self_service',
            'pricing' => [
                'model' => 'custom',
                'currency' => 'RUB',
                'summary' => 'Commercial terms depend on seller profile, catalog size, and fulfillment model.',
            ],
            'url' => '/business/services/b2b-marketplace-onboarding',
        ],
        'digital-voucher-fulfillment' => [
            'name' => 'Digital voucher fulfillment',
            'service_type' => 'fulfillment',
            'audience' => ['marketplaces', 'online shops', 'API merchants'],
            'description' => 'Automated digital voucher issuing, provider stock checks, local inventory support, and customer code delivery.',
            'deliverable' => 'Redeemable voucher code or activation instructions delivered after checkout.',
            'outcome' => 'Customers receive digital goods quickly while sellers retain traceability for every fulfillment event.',
            'delivery_time' => 'seconds to minutes after payment',
            'sla' => 'Automated delivery path with operational traceability',
            'execution_mode' => 'api_and_automated_checkout',
            'pricing' => [
                'model' => 'per_order_or_margin',
                'currency' => 'RUB',
                'summary' => 'Pricing is based on product cost, markup, channel fees, and fulfillment method.',
            ],
            'url' => '/business/services/digital-voucher-fulfillment',
        ],
        'simple-layer-one-clearing' => [
            'name' => 'Payment and operations history',
            'service_type' => 'operations_history',
            'audience' => ['B2B sellers', 'operators', 'finance teams'],
            'description' => 'Clear payment status, Passkey confirmation, balance reservations, and settlement context for digital commerce.',
            'deliverable' => 'Readable operation record with buyer/seller context, balance movement, and support-friendly activity history.',
            'outcome' => 'Commercial operations become auditable across checkout, stock reservation, fulfillment, and settlement.',
            'delivery_time' => 'real time during transaction flow',
            'sla' => 'Operation events are saved as part of the transaction path',
            'execution_mode' => 'embedded_in_checkout',
            'pricing' => [
                'model' => 'platform_usage',
                'currency' => 'RUB',
                'summary' => 'Included in Meanly platform usage or commercial partner agreement.',
            ],
            'url' => '/business/services/simple-layer-one-clearing',
        ],
        'marketplace-channel-adapters' => [
            'name' => 'Marketplace channel adapters',
            'service_type' => 'channel_integration',
            'audience' => ['digital goods sellers', 'marketplace operators'],
            'description' => 'Channel-specific projections from Meanly canonical products into external marketplace listing formats.',
            'deliverable' => 'Channel-ready listing payloads, category mappings, stock sync rules, and validation feedback.',
            'outcome' => 'Sellers can adapt one canonical catalog to multiple external sales channels without making channel categories the source of truth.',
            'delivery_time' => 'depends on channel validation and seller credentials',
            'sla' => 'Mapping and validation are maintained as channel adapters',
            'execution_mode' => 'managed_adapter',
            'pricing' => [
                'model' => 'custom',
                'currency' => 'RUB',
                'summary' => 'Depends on connected channels and operational volume.',
            ],
            'url' => '/business/services/marketplace-channel-adapters',
        ],
    ],
];
