<?php

return [
    'version' => 'v0',
    'principle' => 'graph_is_truth_implementation_is_trace',

    'entry_schema' => [
        'type' => ['core', 'external', 'system', 'implicit'],
        'write_kind' => ['ledger_critical', 'state_derivative', 'external_side_effect', 'mixed_unknown'],
        'risk' => ['low', 'medium', 'high', 'critical'],
        'entrypoint_plane' => ['http', 'queue', 'cli', 'webhook', 'scheduler', 'observer', 'model_hook', 'service'],
        'mutation_scope' => ['financial', 'inventory', 'orders', 'providers', 'system', 'mixed_unknown'],
    ],

    'core_registry_v0_seed' => [
        [
            'name' => 'wallet.debit',
            'business_domain' => 'wallet',
            'mutation_scope' => 'financial',
            'entrypoint_plane' => 'http',
            'type' => 'core',
            'write_kind' => 'ledger_critical',
            'risk' => 'critical',
            'enforcement_required' => true,
            'idempotency_required' => true,
            'ledger_required' => true,
            'confidence' => 'high',
            'depends_on' => [],
            'emits' => ['wallet.ledger_entry', 'sovereign_ledger.transition', 'marketplace_transition_outbox.event'],
            'implementation_sources' => [
                ['file' => 'app/Services/BuyerWalletService.php', 'symbol' => 'debit()', 'evidence_type' => 'direct_write', 'evidence' => 'locks WalletAccount, subtracts available_minor, saves account, creates WalletLedgerEntry, records BUYER_WALLET_DEBIT'],
                ['file' => 'app/Services/Sl1BankCaptureSettlementService.php', 'symbol' => 'reserveSl1ForMultiPay()/commitSl1MultiPay()', 'evidence_type' => 'indirect_write', 'evidence' => 'delegates SL1 reserve/commit to BuyerWalletService wallet mutations'],
            ],
        ],
        [
            'name' => 'order.checkout',
            'business_domain' => 'orders',
            'mutation_scope' => 'financial',
            'entrypoint_plane' => 'http',
            'type' => 'core',
            'write_kind' => 'ledger_critical',
            'risk' => 'critical',
            'enforcement_required' => true,
            'idempotency_required' => true,
            'ledger_required' => true,
            'confidence' => 'high',
            'depends_on' => ['wallet.debit', 'inventory.reserve'],
            'emits' => ['order.created', 'order_item.created', 'sovereign_ledger.transition', 'marketplace_transition_outbox.event'],
            'implementation_sources' => [
                ['file' => 'app/Http/Controllers/MeanlyStorefrontController.php', 'symbol' => 'checkout()', 'evidence_type' => 'indirect_write', 'evidence' => 'delegates checkout mutation to MeanlyRetailCheckoutService and provider fulfillment'],
                ['file' => 'app/Services/MeanlyRetailCheckoutService.php', 'symbol' => 'checkout()', 'evidence_type' => 'direct_write', 'evidence' => 'DB transaction creates orders/order_items, reserves inventory, records ORDER_RECEIVE/FINANCE_CAPTURE'],
                ['file' => 'app/Http/Controllers/Api/WildflowKernelController.php', 'symbol' => 'placeOrder()', 'evidence_type' => 'direct_write', 'evidence' => 'creates MeanlyApiOrder, reserves partner balance, places vendor order, settles/refunds reservation'],
            ],
        ],
        [
            'name' => 'payment.capture',
            'business_domain' => 'payments',
            'mutation_scope' => 'financial',
            'entrypoint_plane' => 'webhook',
            'type' => 'core',
            'write_kind' => 'ledger_critical',
            'risk' => 'critical',
            'enforcement_required' => true,
            'idempotency_required' => true,
            'ledger_required' => true,
            'confidence' => 'high',
            'depends_on' => ['order.checkout'],
            'emits' => ['payment.captured', 'order.paid', 'sovereign_ledger.transition'],
            'implementation_sources' => [
                ['file' => 'app/Services/MeanlyRetailCheckoutService.php', 'symbol' => 'checkout()', 'evidence_type' => 'ledger_append', 'evidence' => 'trusted capture records FINANCE_CAPTURE with wallet ledger proof'],
                ['file' => 'app/Services/Sl1BankCaptureSettlementService.php', 'symbol' => 'captureWithReward()', 'evidence_type' => 'direct_write', 'evidence' => 'locks order, marks payment captured, mints SL1 reward, records BANK_CAPTURE_SL1_REWARD_MINT'],
                ['file' => 'app/Jobs/ProcessRedeemWildflowPurchase.php', 'symbol' => 'captureFundsFromHold()', 'evidence_type' => 'direct_write', 'evidence' => 'decrements reserved balance, marks inventory sold, records FINANCE_CAPTURE'],
            ],
        ],
        [
            'name' => 'provider.yandex.payment_callback',
            'business_domain' => 'providers',
            'mutation_scope' => 'financial',
            'entrypoint_plane' => 'webhook',
            'type' => 'external',
            'write_kind' => 'external_side_effect',
            'risk' => 'critical',
            'enforcement_required' => true,
            'idempotency_required' => true,
            'ledger_required' => true,
            'confidence' => 'medium',
            'depends_on' => ['payment.capture'],
            'emits' => ['provider.notification', 'order.state_changed', 'inventory.adjusted', 'sovereign_ledger.transition'],
            'implementation_sources' => [
                ['file' => 'app/Http/Controllers/Ym/MainController.php', 'symbol' => 'notification()', 'evidence_type' => 'dispatch', 'evidence' => 'persists YmNotification and dispatches ProcessYmNotification'],
                ['file' => 'app/Jobs/ProcessYmNotification.php', 'symbol' => 'handle()', 'evidence_type' => 'indirect_write', 'evidence' => 're-enters OrderController created/updated/arbitrageFinished'],
                ['file' => 'app/Http/Controllers/OrderController.php', 'symbol' => 'created()/updated()', 'evidence_type' => 'direct_write', 'evidence' => 'mutates orders/order_items/inventory/balances and records ledger entries'],
            ],
        ],
        [
            'name' => 'inventory.reserve',
            'business_domain' => 'inventory',
            'mutation_scope' => 'inventory',
            'entrypoint_plane' => 'http',
            'type' => 'core',
            'write_kind' => 'state_derivative',
            'risk' => 'high',
            'enforcement_required' => true,
            'idempotency_required' => true,
            'ledger_required' => true,
            'confidence' => 'high',
            'depends_on' => ['order.checkout'],
            'emits' => ['inventory.reserved', 'warehouse_stock.updated', 'sovereign_ledger.transition'],
            'implementation_sources' => [
                ['file' => 'app/Services/MeanlyRetailCheckoutService.php', 'symbol' => 'reserveVouchers()', 'evidence_type' => 'direct_write', 'evidence' => 'locks/creates ProductInventory, marks sold/reserved, records STOCK_RESERVE'],
                ['file' => 'app/Models/ProductInventory.php', 'symbol' => 'booted() saved callback', 'evidence_type' => 'model_event', 'evidence' => 'updates WarehouseStock and calls StockManagementService on inventory save'],
                ['file' => 'app/Models/ProductInventory.php', 'symbol' => 'liquidate()', 'evidence_type' => 'direct_write', 'evidence' => 'updates legal entity balances, marks inventory liquidated, records FINANCE_RELEASE/STOCK_LIQUIDATE'],
            ],
        ],
        [
            'name' => 'wallet.mint.cli',
            'business_domain' => 'wallet',
            'mutation_scope' => 'financial',
            'entrypoint_plane' => 'cli',
            'type' => 'system',
            'write_kind' => 'ledger_critical',
            'risk' => 'critical',
            'enforcement_required' => true,
            'idempotency_required' => true,
            'ledger_required' => true,
            'confidence' => 'high',
            'depends_on' => [],
            'emits' => ['wallet.ledger_entry', 'sovereign_ledger.transition', 'marketplace_transition_outbox.event'],
            'implementation_sources' => [
                ['file' => 'app/Console/Commands/MintBuyerWalletCommand.php', 'symbol' => 'handle()', 'evidence_type' => 'indirect_write', 'evidence' => 'resolves user, creates idempotency key, calls BuyerWalletService::mintRUBT'],
                ['file' => 'app/Services/BuyerWalletService.php', 'symbol' => 'credit()', 'evidence_type' => 'direct_write', 'evidence' => 'increments WalletAccount, creates WalletLedgerEntry, records BUYER_WALLET_TOPUP'],
            ],
        ],
        [
            'name' => 'payment.retry_job',
            'business_domain' => 'payments',
            'mutation_scope' => 'financial',
            'entrypoint_plane' => 'queue',
            'type' => 'implicit',
            'write_kind' => 'mixed_unknown',
            'risk' => 'critical',
            'enforcement_required' => true,
            'idempotency_required' => true,
            'ledger_required' => true,
            'confidence' => 'medium',
            'depends_on' => ['payment.capture'],
            'emits' => ['payment.retry.attempted', 'provider.order_attempted', 'order_item.updated', 'sovereign_ledger.transition'],
            'implementation_sources' => [
                ['file' => 'app/Console/Commands/RetryFailedPurchases.php', 'symbol' => 'handle()', 'evidence_type' => 'direct_write', 'evidence' => 'increments retry count, creates comments, updates order status, calls OrderService::retryAutozakup'],
                ['file' => 'app/Services/OrderService.php', 'symbol' => 'fulfillAgnostic()', 'evidence_type' => 'external_side_effect', 'evidence' => 'calls provider createOrder/getCodes and mutates order_items'],
                ['file' => 'app/Models/Order/OrderItems.php', 'symbol' => 'booted()', 'evidence_type' => 'model_event', 'evidence' => 'updates parent order progress and records VOUCHER_MANUAL_ADJUSTMENT'],
            ],
        ],
    ],

    'coverage' => [
        'payment.retry_job' => ['status' => 'severely_underprotected', 'priority' => 'p0'],
        'provider.yandex.payment_callback' => ['status' => 'partially_protected', 'priority' => 'p0'],
        'inventory.reserve' => ['status' => 'fragile', 'priority' => 'p0'],
        'wallet.mint.cli' => ['status' => 'dangerous', 'priority' => 'p0'],
    ],

    'placement' => [
        'payment.retry_job' => ['queue_deduplication_layer', 'global_retry_lock', 'service_layer', 'ledger_write_guard', 'writer_epoch_guard'],
        'provider.yandex.payment_callback' => ['webhook_ingress_guard', 'event_dedup_store', 'queue_layer', 'state_machine_transition_guard'],
        'inventory.reserve' => ['model_hook_guard_layer', 'reservation_service_layer', 'transactional_boundary_enforcer', 'row_level_locking_enforcement'],
        'wallet.mint.cli' => ['cli_execution_gate', 'operator_authorization_layer', 'environment_lock', 'writer_epoch_guard', 'audit_append_only_ledger_layer'],
    ],
];
