<?php

return [
    'channels' => [
        'meanly_storefront' => [
            'label' => 'Meanly Storefront',
            'label_en' => 'Meanly Storefront',
            'icon' => 'MS',
            'enabled' => true,
            'implemented' => true,
            'group' => 'owned',
        ],
        'yandex_market' => [
            'label' => 'Яндекс Маркет',
            'label_en' => 'Yandex Market',
            'icon' => '🟡',
            'enabled' => true,
            'implemented' => true,
            'group' => 'marketplaces',
            'markets' => ['ru'],
        ],
        'avito' => [
            'label' => 'Авито',
            'label_en' => 'Avito',
            'icon' => '🟢',
            'enabled' => true,
            'implemented' => false,
            'group' => 'marketplaces',
            'markets' => ['ru'],
        ],
        'wildberries' => [
            'label' => 'Wildberries',
            'label_en' => 'Wildberries',
            'icon' => '🟣',
            'enabled' => true,
            'implemented' => false,
            'group' => 'marketplaces',
            'markets' => ['ru'],
        ],
        'ozon' => [
            'label' => 'Ozon',
            'label_en' => 'Ozon',
            'icon' => '🔵',
            'enabled' => true,
            'implemented' => false,
            'group' => 'marketplaces',
            'markets' => ['ru'],
        ],
        'offline_store' => [
            'label' => 'Оффлайн магазин',
            'label_en' => 'Offline store',
            'icon' => '🏪',
            'enabled' => true,
            'implemented' => true,
            'group' => 'offline',
        ],
        'woocommerce' => [
            'label' => 'WooCommerce',
            'label_en' => 'WooCommerce',
            'icon' => '🛒',
            'enabled' => true,
            'implemented' => true,
            'group' => 'cms',
        ],
        'telegram_bot' => [
            'label' => 'Telegram Bot (Магазин)',
            'label_en' => 'Telegram Shop',
            'icon' => '🤖',
            'enabled' => true,
            'implemented' => false,
            'group' => 'messengers',
            'markets' => ['ru'],
        ],
        'vk_store' => [
            'label' => 'ВКонтакте (Магазин)',
            'label_en' => 'VK Store',
            'icon' => '📱',
            'enabled' => true,
            'implemented' => false,
            'group' => 'messengers',
            'markets' => ['ru'],
        ],
        'whatsapp_business' => [
            'label' => 'WhatsApp Business',
            'label_en' => 'WhatsApp Business',
            'icon' => '💬',
            'enabled' => true,
            'implemented' => false,
            'group' => 'messengers',
        ],
        'messenger_max' => [
            'label' => 'Messenger Max',
            'label_en' => 'Messenger Max',
            'icon' => '⚡',
            'enabled' => true,
            'implemented' => false,
            'group' => 'messengers',
            'markets' => ['ru'],
        ],
    ],
];
