<?php

/**
 * ApiAvailabilityStatusTypeTest
 *
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace AppYandexSdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ApiAvailabilityStatusTypeTest Class Doc Comment
 *
 * @category    Class
 *
 * @description Возможность использовать API:  * &#x60;AVAILABLE&#x60; — методы API доступны для выполнения запросов. * &#x60;DISABLED_BY_INACTIVITY&#x60; — методы API недоступны, так как магазин не размещал товары на витрине больше 90 дней. * &#x60;DISABLED_BY_NO_ACTIVE_CONTRACT&#x60; — методы API недоступны из-за отсутствия активного договора с Маркетом. * &#x60;MANUALLY_DISABLED&#x60; — методы API недоступны, так как интеграция выключена вручную. * &#x60;DISABLED_BY_NO_PLACEMENT_TYPE&#x60; — методы API недоступны, так как магазин не подключен к программе размещения.  [Подробная инструкция по восстановлению доступа](../../concepts/api-access.md)
 *
 * @author      OpenAPI Generator team
 *
 * @link        https://openapi-generator.tech
 */
class ApiAvailabilityStatusTypeTest extends TestCase
{
    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void {}

    /**
     * Setup before running each test case
     */
    protected function setUp(): void {}

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void {}

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void {}

    /**
     * Test "ApiAvailabilityStatusType"
     */
    public function test_api_availability_status_type()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
