<?php

/**
 * CurrencyTypeTest
 *
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace AppYandexSdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CurrencyTypeTest Class Doc Comment
 *
 * @category    Class
 *
 * @description Коды валют:  * &#x60;RUR&#x60; — российский рубль. * &#x60;UAH&#x60; — украинская гривна. * &#x60;BYR&#x60; — белорусский рубль. * &#x60;KZT&#x60; — казахстанский тенге. * &#x60;UZS&#x60; — узбекский сум.
 *
 * @author      OpenAPI Generator team
 *
 * @link        https://openapi-generator.tech
 */
class CurrencyTypeTest extends TestCase
{
    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void {}

    /**
     * Setup before running each test case
     */
    protected function setUp(): void {}

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void {}

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void {}

    /**
     * Test "CurrencyType"
     */
    public function test_currency_type()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
