<?php

/**
 * GenerateStocksOnWarehousesReportRequestTest
 *
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace AppYandexSdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GenerateStocksOnWarehousesReportRequestTest Class Doc Comment
 *
 * @category    Class
 *
 * @description Данные, необходимые для генерации отчета. Передавайте либо &#x60;businessId&#x60;, либо &#x60;campaignId&#x60;/&#x60;campaignIds&#x60;, но не все сразу.
 *
 * @author      OpenAPI Generator team
 *
 * @link        https://openapi-generator.tech
 */
class GenerateStocksOnWarehousesReportRequestTest extends TestCase
{
    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void {}

    /**
     * Setup before running each test case
     */
    protected function setUp(): void {}

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void {}

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void {}

    /**
     * Test "GenerateStocksOnWarehousesReportRequest"
     */
    public function test_generate_stocks_on_warehouses_report_request()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "campaign_id"
     */
    public function test_property_campaign_id()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "business_id"
     */
    public function test_property_business_id()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "warehouse_ids"
     */
    public function test_property_warehouse_ids()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "report_date"
     */
    public function test_property_report_date()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "category_ids"
     */
    public function test_property_category_ids()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "has_stocks"
     */
    public function test_property_has_stocks()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "campaign_ids"
     */
    public function test_property_campaign_ids()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
