<?php

/**
 * OrderDeliveryEacTypeTest
 *
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace AppYandexSdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * OrderDeliveryEacTypeTest Class Doc Comment
 *
 * @category    Class
 *
 * @description Тип кода подтверждения ЭАПП:  * &#x60;MERCHANT_TO_COURIER&#x60; (временно не возвращается) — продавец передает код курьеру для получения невыкупа.  * &#x60;COURIER_TO_MERCHANT&#x60; — курьер передает код продавцу для получения заказа.  * &#x60;CHECKING_BY_MERCHANT&#x60; — продавец проверяет код на своей стороне.
 *
 * @author      OpenAPI Generator team
 *
 * @link        https://openapi-generator.tech
 */
class OrderDeliveryEacTypeTest extends TestCase
{
    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void {}

    /**
     * Setup before running each test case
     */
    protected function setUp(): void {}

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void {}

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void {}

    /**
     * Test "OrderDeliveryEacType"
     */
    public function test_order_delivery_eac_type()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
