<?php

/**
 * ReturnRequestDecisionReasonTypeTest
 *
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace AppYandexSdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ReturnRequestDecisionReasonTypeTest Class Doc Comment
 *
 * @category    Class
 *
 * @description Причина отказа:  * &#x60;ISSUE_WITH_THE_PRODUCT_WAS_NOT_CONFIRMED&#x60; — проблема с товаром не подтвердилась. * &#x60;MECHANICAL_DAMAGE&#x60; — есть механические повреждения товара. * &#x60;WARRANTY_PERIOD_HAS_EXPIRED&#x60; — истек гарантийный срок. * &#x60;CONFIGURATION_OR_PACKAGING_COMPROMISED&#x60; — нарушена комплектация или упаковка. * &#x60;PRODUCT_APPEARANCE_COMPROMISED&#x60; — нарушен товарный вид. * &#x60;WARRANTY_TERMS_VIOLATED&#x60; — нарушены условия гарантии. * &#x60;DEVICE_ACTIVATED&#x60; — устройство активировано.
 *
 * @author      OpenAPI Generator team
 *
 * @link        https://openapi-generator.tech
 */
class ReturnRequestDecisionReasonTypeTest extends TestCase
{
    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void {}

    /**
     * Setup before running each test case
     */
    protected function setUp(): void {}

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void {}

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void {}

    /**
     * Test "ReturnRequestDecisionReasonType"
     */
    public function test_return_request_decision_reason_type()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
