<?php

/**
 * SupplyRequestReferenceTypeTest
 *
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace AppYandexSdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * SupplyRequestReferenceTypeTest Class Doc Comment
 *
 * @category    Class
 *
 * @description Тип связи между двумя заявками:  * &#x60;VIRTUAL_DISTRIBUTION&#x60; — [мультипоставка](*multisupply).  * &#x60;WITHDRAW&#x60; — вывоз непринятых товаров.      Подтипы заявки: &#x60;DEFAULT&#x60;, &#x60;XDOC&#x60;, &#x60;VIRTUAL_DISTRIBUTION_CENTER_CHILD&#x60; и &#x60;ANOMALY_WITHDRAW&#x60;.  * &#x60;UTILIZATION&#x60; — утилизация непринятых товаров.      Подтипы заявки: &#x60;DEFAULT&#x60;, &#x60;XDOC&#x60;, &#x60;VIRTUAL_DISTRIBUTION_CENTER_CHILD&#x60; и &#x60;FORCE_PLAN_ANOMALY_PER_SUPPLY&#x60;.  * &#x60;ADDITIONAL_SUPPLY&#x60; — дополнительная поставка.      Подтипы заявки: &#x60;DEFAULT&#x60;, &#x60;XDOC&#x60;, &#x60;VIRTUAL_DISTRIBUTION_CENTER_CHILD&#x60; и &#x60;ADDITIONAL_SUPPLY&#x60;.
 *
 * @author      OpenAPI Generator team
 *
 * @link        https://openapi-generator.tech
 */
class SupplyRequestReferenceTypeTest extends TestCase
{
    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void {}

    /**
     * Setup before running each test case
     */
    protected function setUp(): void {}

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void {}

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void {}

    /**
     * Test "SupplyRequestReferenceType"
     */
    public function test_supply_request_reference_type()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
