<?php

/**
 * SupplyRequestDocumentTypeTest
 *
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace AppYandexSdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * SupplyRequestDocumentTypeTest Class Doc Comment
 *
 * @category    Class
 *
 * @description Тип документа:  * **Документы, которые загружает магазин**   * &#x60;SUPPLY&#x60; — список товаров.   * &#x60;ADDITIONAL_SUPPLY&#x60; — список товаров в дополнительной поставке.   * &#x60;VIRTUAL_DISTRIBUTION_CENTER_SUPPLY&#x60; — список товаров в [мультипоставке](*multisupply).   * &#x60;TRANSFER&#x60; — список товаров для утилизации.   * &#x60;WITHDRAW&#x60; — список товаров для вывоза.  * **Поставка товаров**   * &#x60;VALIDATION_ERRORS&#x60; — ошибки по товарам в поставке.   * &#x60;CARGO_UNITS&#x60; — ярлыки для грузомест.  * **Дополнительная поставка и непринятые товары**   * &#x60;ADDITIONAL_SUPPLY_ACCEPTABLE_GOODS&#x60; — товары, которые подходят для дополнительной поставки.   * &#x60;ADDITIONAL_SUPPLY_UNACCEPTABLE_GOODS&#x60; — вывоз непринятых товаров.  * **Маркировка товаров**   * &#x60;INBOUND_UTD&#x60; — входящий УПД.   * &#x60;OUTBOUND_UTD&#x60; — исходящий УПД.   * &#x60;IDENTIFIERS&#x60; — коды маркировки товаров.   * &#x60;CIS_FACT&#x60; — принятые товары с кодами маркировки.   * &#x60;ITEMS_WITH_CISES&#x60; — товары, для которых нужна маркировка.   * &#x60;REPORT_OF_WITHDRAW_WITH_CISES&#x60; — маркированные товары для вывоза со склада.   * &#x60;SECONDARY_ACCEPTANCE_CISES&#x60; — маркированные товары, которые приняты после вторичной приемки.   * &#x60;RNPT_FACT&#x60; — принятые товары с регистрационным номером партии товара (РНПТ).  * **Акты**   * &#x60;ACT_OF_WITHDRAW&#x60; — акт возврата.   * &#x60;ANOMALY_CONTAINERS_WITHDRAW_ACT&#x60; — акт изъятия непринятого товара.   * &#x60;ACT_OF_WITHDRAW_FROM_STORAGE&#x60; — акт списания с ответственного хранения.   * &#x60;ACT_OF_RECEPTION_TRANSFER&#x60; — акт приема-передачи.   * &#x60;ACT_OF_DISCREPANCY&#x60; — акт о расхождениях.   * &#x60;SECONDARY_RECEPTION_ACT&#x60; — акт вторичной приемки.
 *
 * @author      OpenAPI Generator team
 *
 * @link        https://openapi-generator.tech
 */
class SupplyRequestDocumentTypeTest extends TestCase
{
    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void {}

    /**
     * Setup before running each test case
     */
    protected function setUp(): void {}

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void {}

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void {}

    /**
     * Test "SupplyRequestDocumentType"
     */
    public function test_supply_request_document_type()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
