<?php

/**
 * UpdatePromoOfferDiscountParamsDTOTest
 *
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace AppYandexSdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * UpdatePromoOfferDiscountParamsDTOTest Class Doc Comment
 *
 * @category    Class
 *
 * @description Параметры товара в акции с типом &#x60;DIRECT_DISCOUNT&#x60; или &#x60;BLUE_FLASH&#x60;.  Обязательный параметр для акций с этими типами.
 *
 * @author      OpenAPI Generator team
 *
 * @link        https://openapi-generator.tech
 */
class UpdatePromoOfferDiscountParamsDTOTest extends TestCase
{
    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void {}

    /**
     * Setup before running each test case
     */
    protected function setUp(): void {}

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void {}

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void {}

    /**
     * Test "UpdatePromoOfferDiscountParamsDTO"
     */
    public function test_update_promo_offer_discount_params_dto()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "price"
     */
    public function test_property_price()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "promo_price"
     */
    public function test_property_promo_price()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
