<?php

namespace App\Enums\Yandex;

/**
 * Generated from Yandex Market OpenAPI spec
 * Этап обработки заказа (статус `PROCESSING`) или причина отмены заказа (статус `CANCELLED`).
 *
 * * Значения для заказа в статусе `PROCESSING`:
 *
 *     * `STARTED` — заказ подтвержден, его можно начать обрабатывать.
 *
 *     * `READY_TO_SHIP` — заказ собран и готов к отправке.
 * * Значения для заказа в статусе `CANCELLED`:
 *
 *     * `RESERVATION_EXPIRED` — покупатель не завершил оформление зарезервированного заказа в течение 10 минут.
 *
 *     * `USER_NOT_PAID` — покупатель не оплатил заказ (для типа оплаты `PREPAID`) в течение 30 минут.
 *
 *     * `USER_UNREACHABLE` — не удалось связаться с покупателем. Для отмены с этой причиной необходимо выполнить условия:
 *
 *       * не менее 3 звонков с 8 до 21 в часовом поясе покупателя;
 *       * перерыв между первым и третьим звонком не менее 90 минут;
 *       * соединение не короче 5 секунд.
 *
 *       Если хотя бы одно из этих условий не выполнено (кроме случая, когда номер недоступен), отменить заказ не получится. Вернется ответ с кодом ошибки 400.
 *
 *     * `USER_CHANGED_MIND` — покупатель отменил заказ по личным причинам.
 *
 *     * `USER_REFUSED_DELIVERY` — покупателя не устроили условия доставки.
 *
 *     * `USER_REFUSED_PRODUCT` — покупателю не подошел товар.
 *
 *     * `SHOP_FAILED` — магазин не может выполнить заказ.
 *
 *     * `USER_REFUSED_QUALITY` — покупателя не устроило качество товара.
 *
 *     * `REPLACING_ORDER` — покупатель решил заменить товар другим по собственной инициативе.
 *
 *     * `PROCESSING_EXPIRED` — значение более не используется.
 *
 *     * `PICKUP_EXPIRED` — закончился срок хранения заказа в пункт выдачи.
 *
 *     * `TOO_MANY_DELIVERY_DATE_CHANGES` — заказ переносили слишком много раз.
 *
 *     * `TOO_LONG_DELIVERY` — заказ доставляется слишком долго.
 *
 *     * `INCORRECT_PERSONAL_DATA` — для заказа из-за рубежа указаны неправильные данные получателя, заказ не пройдет проверку на таможне.
 * * `TECHNICAL_ERROR` — техническая ошибка на стороне Маркета. Обратитесь в поддержку.
 *
 * Также могут возвращаться другие значения. Обрабатывать их не нужно.
 */
enum YmOrderSubstatus: string
{
    case RESERVATION_EXPIRED = 'RESERVATION_EXPIRED';
    case USER_NOT_PAID = 'USER_NOT_PAID';
    case USER_UNREACHABLE = 'USER_UNREACHABLE';
    case USER_CHANGED_MIND = 'USER_CHANGED_MIND';
    case USER_REFUSED_DELIVERY = 'USER_REFUSED_DELIVERY';
    case USER_REFUSED_PRODUCT = 'USER_REFUSED_PRODUCT';
    case SHOP_FAILED = 'SHOP_FAILED';
    case USER_REFUSED_QUALITY = 'USER_REFUSED_QUALITY';
    case REPLACING_ORDER = 'REPLACING_ORDER';
    case PROCESSING_EXPIRED = 'PROCESSING_EXPIRED';
    case PENDING_EXPIRED = 'PENDING_EXPIRED';
    case SHOP_PENDING_CANCELLED = 'SHOP_PENDING_CANCELLED';
    case PENDING_CANCELLED = 'PENDING_CANCELLED';
    case USER_FRAUD = 'USER_FRAUD';
    case RESERVATION_FAILED = 'RESERVATION_FAILED';
    case USER_PLACED_OTHER_ORDER = 'USER_PLACED_OTHER_ORDER';
    case USER_BOUGHT_CHEAPER = 'USER_BOUGHT_CHEAPER';
    case MISSING_ITEM = 'MISSING_ITEM';
    case BROKEN_ITEM = 'BROKEN_ITEM';
    case WRONG_ITEM = 'WRONG_ITEM';
    case PICKUP_EXPIRED = 'PICKUP_EXPIRED';
    case DELIVERY_PROBLEMS = 'DELIVERY_PROBLEMS';
    case LATE_CONTACT = 'LATE_CONTACT';
    case CUSTOM = 'CUSTOM';
    case DELIVERY_SERVICE_FAILED = 'DELIVERY_SERVICE_FAILED';
    case WAREHOUSE_FAILED_TO_SHIP = 'WAREHOUSE_FAILED_TO_SHIP';
    case DELIVERY_SERVICE_UNDELIVERED = 'DELIVERY_SERVICE_UNDELIVERED';
    case PREORDER = 'PREORDER';
    case AWAIT_CONFIRMATION = 'AWAIT_CONFIRMATION';
    case STARTED = 'STARTED';
    case PACKAGING = 'PACKAGING';
    case READY_TO_SHIP = 'READY_TO_SHIP';
    case SHIPPED = 'SHIPPED';
    case ASYNC_PROCESSING = 'ASYNC_PROCESSING';
    case WAITING_USER_INPUT = 'WAITING_USER_INPUT';
    case WAITING_BANK_DECISION = 'WAITING_BANK_DECISION';
    case BANK_REJECT_CREDIT_OFFER = 'BANK_REJECT_CREDIT_OFFER';
    case CUSTOMER_REJECT_CREDIT_OFFER = 'CUSTOMER_REJECT_CREDIT_OFFER';
    case CREDIT_OFFER_FAILED = 'CREDIT_OFFER_FAILED';
    case AWAIT_DELIVERY_DATES_CONFIRMATION = 'AWAIT_DELIVERY_DATES_CONFIRMATION';
    case SERVICE_FAULT = 'SERVICE_FAULT';
    case DELIVERY_SERVICE_RECEIVED = 'DELIVERY_SERVICE_RECEIVED';
    case USER_RECEIVED = 'USER_RECEIVED';
    case WAITING_FOR_STOCKS = 'WAITING_FOR_STOCKS';
    case AS_PART_OF_MULTI_ORDER = 'AS_PART_OF_MULTI_ORDER';
    case READY_FOR_LAST_MILE = 'READY_FOR_LAST_MILE';
    case LAST_MILE_STARTED = 'LAST_MILE_STARTED';
    case ANTIFRAUD = 'ANTIFRAUD';
    case DELIVERY_USER_NOT_RECEIVED = 'DELIVERY_USER_NOT_RECEIVED';
    case DELIVERY_SERVICE_DELIVERED = 'DELIVERY_SERVICE_DELIVERED';
    case DELIVERED_USER_NOT_RECEIVED = 'DELIVERED_USER_NOT_RECEIVED';
    case USER_WANTED_ANOTHER_PAYMENT_METHOD = 'USER_WANTED_ANOTHER_PAYMENT_METHOD';
    case USER_RECEIVED_TECHNICAL_ERROR = 'USER_RECEIVED_TECHNICAL_ERROR';
    case USER_FORGOT_TO_USE_BONUS = 'USER_FORGOT_TO_USE_BONUS';
    case DELIVERY_SERVICE_NOT_RECEIVED = 'DELIVERY_SERVICE_NOT_RECEIVED';
    case DELIVERY_SERVICE_LOST = 'DELIVERY_SERVICE_LOST';
    case SHIPPED_TO_WRONG_DELIVERY_SERVICE = 'SHIPPED_TO_WRONG_DELIVERY_SERVICE';
    case DELIVERED_USER_RECEIVED = 'DELIVERED_USER_RECEIVED';
    case WAITING_TINKOFF_DECISION = 'WAITING_TINKOFF_DECISION';
    case COURIER_SEARCH = 'COURIER_SEARCH';
    case COURIER_FOUND = 'COURIER_FOUND';
    case COURIER_IN_TRANSIT_TO_SENDER = 'COURIER_IN_TRANSIT_TO_SENDER';
    case COURIER_ARRIVED_TO_SENDER = 'COURIER_ARRIVED_TO_SENDER';
    case COURIER_RECEIVED = 'COURIER_RECEIVED';
    case COURIER_NOT_FOUND = 'COURIER_NOT_FOUND';
    case COURIER_NOT_DELIVER_ORDER = 'COURIER_NOT_DELIVER_ORDER';
    case COURIER_RETURNS_ORDER = 'COURIER_RETURNS_ORDER';
    case COURIER_RETURNED_ORDER = 'COURIER_RETURNED_ORDER';
    case WAITING_USER_DELIVERY_INPUT = 'WAITING_USER_DELIVERY_INPUT';
    case PICKUP_SERVICE_RECEIVED = 'PICKUP_SERVICE_RECEIVED';
    case PICKUP_USER_RECEIVED = 'PICKUP_USER_RECEIVED';
    case CANCELLED_COURIER_NOT_FOUND = 'CANCELLED_COURIER_NOT_FOUND';
    case COURIER_NOT_COME_FOR_ORDER = 'COURIER_NOT_COME_FOR_ORDER';
    case DELIVERY_NOT_MANAGED_REGION = 'DELIVERY_NOT_MANAGED_REGION';
    case INCOMPLETE_CONTACT_INFORMATION = 'INCOMPLETE_CONTACT_INFORMATION';
    case INCOMPLETE_MULTI_ORDER = 'INCOMPLETE_MULTI_ORDER';
    case INAPPROPRIATE_WEIGHT_SIZE = 'INAPPROPRIATE_WEIGHT_SIZE';
    case TECHNICAL_ERROR = 'TECHNICAL_ERROR';
    case SORTING_CENTER_LOST = 'SORTING_CENTER_LOST';
    case COURIER_SEARCH_NOT_STARTED = 'COURIER_SEARCH_NOT_STARTED';
    case LOST = 'LOST';
    case AWAIT_PAYMENT = 'AWAIT_PAYMENT';
    case AWAIT_LAVKA_RESERVATION = 'AWAIT_LAVKA_RESERVATION';
    case USER_WANTS_TO_CHANGE_ADDRESS = 'USER_WANTS_TO_CHANGE_ADDRESS';
    case FULL_NOT_RANSOM = 'FULL_NOT_RANSOM';
    case PRESCRIPTION_MISMATCH = 'PRESCRIPTION_MISMATCH';
    case DROPOFF_LOST = 'DROPOFF_LOST';
    case DROPOFF_CLOSED = 'DROPOFF_CLOSED';
    case DELIVERY_TO_STORE_STARTED = 'DELIVERY_TO_STORE_STARTED';
    case USER_WANTS_TO_CHANGE_DELIVERY_DATE = 'USER_WANTS_TO_CHANGE_DELIVERY_DATE';
    case WRONG_ITEM_DELIVERED = 'WRONG_ITEM_DELIVERED';
    case DAMAGED_BOX = 'DAMAGED_BOX';
    case AWAIT_DELIVERY_DATES = 'AWAIT_DELIVERY_DATES';
    case LAST_MILE_COURIER_SEARCH = 'LAST_MILE_COURIER_SEARCH';
    case PICKUP_POINT_CLOSED = 'PICKUP_POINT_CLOSED';
    case LEGAL_INFO_CHANGED = 'LEGAL_INFO_CHANGED';
    case USER_HAS_NO_TIME_TO_PICKUP_ORDER = 'USER_HAS_NO_TIME_TO_PICKUP_ORDER';
    case DELIVERY_CUSTOMS_ARRIVED = 'DELIVERY_CUSTOMS_ARRIVED';
    case DELIVERY_CUSTOMS_CLEARED = 'DELIVERY_CUSTOMS_CLEARED';
    case FIRST_MILE_DELIVERY_SERVICE_RECEIVED = 'FIRST_MILE_DELIVERY_SERVICE_RECEIVED';
    case AWAIT_AUTO_DELIVERY_DATES = 'AWAIT_AUTO_DELIVERY_DATES';
    case AWAIT_USER_PERSONAL_DATA = 'AWAIT_USER_PERSONAL_DATA';
    case NO_PERSONAL_DATA_EXPIRED = 'NO_PERSONAL_DATA_EXPIRED';
    case CUSTOMS_PROBLEMS = 'CUSTOMS_PROBLEMS';
    case AWAIT_CASHIER = 'AWAIT_CASHIER';
    case WAITING_POSTPAID_BUDGET_RESERVATION = 'WAITING_POSTPAID_BUDGET_RESERVATION';
    case AWAIT_SERVICEABLE_CONFIRMATION = 'AWAIT_SERVICEABLE_CONFIRMATION';
    case POSTPAID_BUDGET_RESERVATION_FAILED = 'POSTPAID_BUDGET_RESERVATION_FAILED';
    case AWAIT_CUSTOM_PRICE_CONFIRMATION = 'AWAIT_CUSTOM_PRICE_CONFIRMATION';
    case READY_FOR_PICKUP = 'READY_FOR_PICKUP';
    case TOO_MANY_DELIVERY_DATE_CHANGES = 'TOO_MANY_DELIVERY_DATE_CHANGES';
    case TOO_LONG_DELIVERY = 'TOO_LONG_DELIVERY';
    case DEFERRED_PAYMENT = 'DEFERRED_PAYMENT';
    case POSTPAID_FAILED = 'POSTPAID_FAILED';
    case INCORRECT_PERSONAL_DATA = 'INCORRECT_PERSONAL_DATA';
    case CUSTOMS_FAILED_MARKET = 'CUSTOMS_FAILED_MARKET';
    case CUSTOMS_FAILED_USER_COMMERCIAL_ITEMS = 'CUSTOMS_FAILED_USER_COMMERCIAL_ITEMS';
    case CUSTOMS_FAILED_USER_DUTY_NOT_PAID = 'CUSTOMS_FAILED_USER_DUTY_NOT_PAID';
    case CUSTOMS_FAILED_USER_INVALID_PERSONAL_DATA = 'CUSTOMS_FAILED_USER_INVALID_PERSONAL_DATA';
    case CUSTOMS_FAILED_USER_ADDITIONAL_DATA_NOT_PROVIDED = 'CUSTOMS_FAILED_USER_ADDITIONAL_DATA_NOT_PROVIDED';
    case AWAIT_PAYMENT_AFTER_DELIVERY = 'AWAIT_PAYMENT_AFTER_DELIVERY';
    case AWAIT_USER_STEAM_FAST_URL = 'AWAIT_USER_STEAM_FAST_URL';
    case UNKNOWN = 'UNKNOWN';

    public function label(): string
    {
        return match ($this) {
            self::RESERVATION_EXPIRED => 'RESERVATION_EXPIRED',
            self::USER_NOT_PAID => 'USER_NOT_PAID',
            self::USER_UNREACHABLE => 'USER_UNREACHABLE',
            self::USER_CHANGED_MIND => 'USER_CHANGED_MIND',
            self::USER_REFUSED_DELIVERY => 'USER_REFUSED_DELIVERY',
            self::USER_REFUSED_PRODUCT => 'USER_REFUSED_PRODUCT',
            self::SHOP_FAILED => 'SHOP_FAILED',
            self::USER_REFUSED_QUALITY => 'USER_REFUSED_QUALITY',
            self::REPLACING_ORDER => 'REPLACING_ORDER',
            self::PROCESSING_EXPIRED => 'PROCESSING_EXPIRED',
            self::PENDING_EXPIRED => 'PENDING_EXPIRED',
            self::SHOP_PENDING_CANCELLED => 'SHOP_PENDING_CANCELLED',
            self::PENDING_CANCELLED => 'PENDING_CANCELLED',
            self::USER_FRAUD => 'USER_FRAUD',
            self::RESERVATION_FAILED => 'RESERVATION_FAILED',
            self::USER_PLACED_OTHER_ORDER => 'USER_PLACED_OTHER_ORDER',
            self::USER_BOUGHT_CHEAPER => 'USER_BOUGHT_CHEAPER',
            self::MISSING_ITEM => 'MISSING_ITEM',
            self::BROKEN_ITEM => 'BROKEN_ITEM',
            self::WRONG_ITEM => 'WRONG_ITEM',
            self::PICKUP_EXPIRED => 'PICKUP_EXPIRED',
            self::DELIVERY_PROBLEMS => 'DELIVERY_PROBLEMS',
            self::LATE_CONTACT => 'LATE_CONTACT',
            self::CUSTOM => 'CUSTOM',
            self::DELIVERY_SERVICE_FAILED => 'DELIVERY_SERVICE_FAILED',
            self::WAREHOUSE_FAILED_TO_SHIP => 'WAREHOUSE_FAILED_TO_SHIP',
            self::DELIVERY_SERVICE_UNDELIVERED => 'DELIVERY_SERVICE_UNDELIVERED',
            self::PREORDER => 'PREORDER',
            self::AWAIT_CONFIRMATION => 'AWAIT_CONFIRMATION',
            self::STARTED => 'STARTED',
            self::PACKAGING => 'PACKAGING',
            self::READY_TO_SHIP => 'READY_TO_SHIP',
            self::SHIPPED => 'SHIPPED',
            self::ASYNC_PROCESSING => 'ASYNC_PROCESSING',
            self::WAITING_USER_INPUT => 'WAITING_USER_INPUT',
            self::WAITING_BANK_DECISION => 'WAITING_BANK_DECISION',
            self::BANK_REJECT_CREDIT_OFFER => 'BANK_REJECT_CREDIT_OFFER',
            self::CUSTOMER_REJECT_CREDIT_OFFER => 'CUSTOMER_REJECT_CREDIT_OFFER',
            self::CREDIT_OFFER_FAILED => 'CREDIT_OFFER_FAILED',
            self::AWAIT_DELIVERY_DATES_CONFIRMATION => 'AWAIT_DELIVERY_DATES_CONFIRMATION',
            self::SERVICE_FAULT => 'SERVICE_FAULT',
            self::DELIVERY_SERVICE_RECEIVED => 'DELIVERY_SERVICE_RECEIVED',
            self::USER_RECEIVED => 'USER_RECEIVED',
            self::WAITING_FOR_STOCKS => 'WAITING_FOR_STOCKS',
            self::AS_PART_OF_MULTI_ORDER => 'AS_PART_OF_MULTI_ORDER',
            self::READY_FOR_LAST_MILE => 'READY_FOR_LAST_MILE',
            self::LAST_MILE_STARTED => 'LAST_MILE_STARTED',
            self::ANTIFRAUD => 'ANTIFRAUD',
            self::DELIVERY_USER_NOT_RECEIVED => 'DELIVERY_USER_NOT_RECEIVED',
            self::DELIVERY_SERVICE_DELIVERED => 'DELIVERY_SERVICE_DELIVERED',
            self::DELIVERED_USER_NOT_RECEIVED => 'DELIVERED_USER_NOT_RECEIVED',
            self::USER_WANTED_ANOTHER_PAYMENT_METHOD => 'USER_WANTED_ANOTHER_PAYMENT_METHOD',
            self::USER_RECEIVED_TECHNICAL_ERROR => 'USER_RECEIVED_TECHNICAL_ERROR',
            self::USER_FORGOT_TO_USE_BONUS => 'USER_FORGOT_TO_USE_BONUS',
            self::DELIVERY_SERVICE_NOT_RECEIVED => 'DELIVERY_SERVICE_NOT_RECEIVED',
            self::DELIVERY_SERVICE_LOST => 'DELIVERY_SERVICE_LOST',
            self::SHIPPED_TO_WRONG_DELIVERY_SERVICE => 'SHIPPED_TO_WRONG_DELIVERY_SERVICE',
            self::DELIVERED_USER_RECEIVED => 'DELIVERED_USER_RECEIVED',
            self::WAITING_TINKOFF_DECISION => 'WAITING_TINKOFF_DECISION',
            self::COURIER_SEARCH => 'COURIER_SEARCH',
            self::COURIER_FOUND => 'COURIER_FOUND',
            self::COURIER_IN_TRANSIT_TO_SENDER => 'COURIER_IN_TRANSIT_TO_SENDER',
            self::COURIER_ARRIVED_TO_SENDER => 'COURIER_ARRIVED_TO_SENDER',
            self::COURIER_RECEIVED => 'COURIER_RECEIVED',
            self::COURIER_NOT_FOUND => 'COURIER_NOT_FOUND',
            self::COURIER_NOT_DELIVER_ORDER => 'COURIER_NOT_DELIVER_ORDER',
            self::COURIER_RETURNS_ORDER => 'COURIER_RETURNS_ORDER',
            self::COURIER_RETURNED_ORDER => 'COURIER_RETURNED_ORDER',
            self::WAITING_USER_DELIVERY_INPUT => 'WAITING_USER_DELIVERY_INPUT',
            self::PICKUP_SERVICE_RECEIVED => 'PICKUP_SERVICE_RECEIVED',
            self::PICKUP_USER_RECEIVED => 'PICKUP_USER_RECEIVED',
            self::CANCELLED_COURIER_NOT_FOUND => 'CANCELLED_COURIER_NOT_FOUND',
            self::COURIER_NOT_COME_FOR_ORDER => 'COURIER_NOT_COME_FOR_ORDER',
            self::DELIVERY_NOT_MANAGED_REGION => 'DELIVERY_NOT_MANAGED_REGION',
            self::INCOMPLETE_CONTACT_INFORMATION => 'INCOMPLETE_CONTACT_INFORMATION',
            self::INCOMPLETE_MULTI_ORDER => 'INCOMPLETE_MULTI_ORDER',
            self::INAPPROPRIATE_WEIGHT_SIZE => 'INAPPROPRIATE_WEIGHT_SIZE',
            self::TECHNICAL_ERROR => 'TECHNICAL_ERROR',
            self::SORTING_CENTER_LOST => 'SORTING_CENTER_LOST',
            self::COURIER_SEARCH_NOT_STARTED => 'COURIER_SEARCH_NOT_STARTED',
            self::LOST => 'LOST',
            self::AWAIT_PAYMENT => 'AWAIT_PAYMENT',
            self::AWAIT_LAVKA_RESERVATION => 'AWAIT_LAVKA_RESERVATION',
            self::USER_WANTS_TO_CHANGE_ADDRESS => 'USER_WANTS_TO_CHANGE_ADDRESS',
            self::FULL_NOT_RANSOM => 'FULL_NOT_RANSOM',
            self::PRESCRIPTION_MISMATCH => 'PRESCRIPTION_MISMATCH',
            self::DROPOFF_LOST => 'DROPOFF_LOST',
            self::DROPOFF_CLOSED => 'DROPOFF_CLOSED',
            self::DELIVERY_TO_STORE_STARTED => 'DELIVERY_TO_STORE_STARTED',
            self::USER_WANTS_TO_CHANGE_DELIVERY_DATE => 'USER_WANTS_TO_CHANGE_DELIVERY_DATE',
            self::WRONG_ITEM_DELIVERED => 'WRONG_ITEM_DELIVERED',
            self::DAMAGED_BOX => 'DAMAGED_BOX',
            self::AWAIT_DELIVERY_DATES => 'AWAIT_DELIVERY_DATES',
            self::LAST_MILE_COURIER_SEARCH => 'LAST_MILE_COURIER_SEARCH',
            self::PICKUP_POINT_CLOSED => 'PICKUP_POINT_CLOSED',
            self::LEGAL_INFO_CHANGED => 'LEGAL_INFO_CHANGED',
            self::USER_HAS_NO_TIME_TO_PICKUP_ORDER => 'USER_HAS_NO_TIME_TO_PICKUP_ORDER',
            self::DELIVERY_CUSTOMS_ARRIVED => 'DELIVERY_CUSTOMS_ARRIVED',
            self::DELIVERY_CUSTOMS_CLEARED => 'DELIVERY_CUSTOMS_CLEARED',
            self::FIRST_MILE_DELIVERY_SERVICE_RECEIVED => 'FIRST_MILE_DELIVERY_SERVICE_RECEIVED',
            self::AWAIT_AUTO_DELIVERY_DATES => 'AWAIT_AUTO_DELIVERY_DATES',
            self::AWAIT_USER_PERSONAL_DATA => 'AWAIT_USER_PERSONAL_DATA',
            self::NO_PERSONAL_DATA_EXPIRED => 'NO_PERSONAL_DATA_EXPIRED',
            self::CUSTOMS_PROBLEMS => 'CUSTOMS_PROBLEMS',
            self::AWAIT_CASHIER => 'AWAIT_CASHIER',
            self::WAITING_POSTPAID_BUDGET_RESERVATION => 'WAITING_POSTPAID_BUDGET_RESERVATION',
            self::AWAIT_SERVICEABLE_CONFIRMATION => 'AWAIT_SERVICEABLE_CONFIRMATION',
            self::POSTPAID_BUDGET_RESERVATION_FAILED => 'POSTPAID_BUDGET_RESERVATION_FAILED',
            self::AWAIT_CUSTOM_PRICE_CONFIRMATION => 'AWAIT_CUSTOM_PRICE_CONFIRMATION',
            self::READY_FOR_PICKUP => 'READY_FOR_PICKUP',
            self::TOO_MANY_DELIVERY_DATE_CHANGES => 'TOO_MANY_DELIVERY_DATE_CHANGES',
            self::TOO_LONG_DELIVERY => 'TOO_LONG_DELIVERY',
            self::DEFERRED_PAYMENT => 'DEFERRED_PAYMENT',
            self::POSTPAID_FAILED => 'POSTPAID_FAILED',
            self::INCORRECT_PERSONAL_DATA => 'INCORRECT_PERSONAL_DATA',
            self::CUSTOMS_FAILED_MARKET => 'CUSTOMS_FAILED_MARKET',
            self::CUSTOMS_FAILED_USER_COMMERCIAL_ITEMS => 'CUSTOMS_FAILED_USER_COMMERCIAL_ITEMS',
            self::CUSTOMS_FAILED_USER_DUTY_NOT_PAID => 'CUSTOMS_FAILED_USER_DUTY_NOT_PAID',
            self::CUSTOMS_FAILED_USER_INVALID_PERSONAL_DATA => 'CUSTOMS_FAILED_USER_INVALID_PERSONAL_DATA',
            self::CUSTOMS_FAILED_USER_ADDITIONAL_DATA_NOT_PROVIDED => 'CUSTOMS_FAILED_USER_ADDITIONAL_DATA_NOT_PROVIDED',
            self::AWAIT_PAYMENT_AFTER_DELIVERY => 'AWAIT_PAYMENT_AFTER_DELIVERY',
            self::AWAIT_USER_STEAM_FAST_URL => 'AWAIT_USER_STEAM_FAST_URL',
            self::UNKNOWN => 'UNKNOWN',
        };
    }
}
